
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class ShipAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {13555, -1, -1, 6}, {13422, -1, -1, 4}, {13422, 0, -3, 4}// 1	2	3	
			, {7020, -1, -1, 4}, {8, 3, -2, 4}, {8, 3, 1, 4}// 4	5	6	
			, {8, 3, 0, 4}, {8, 3, -1, 4}, {8, 3, -3, 4}// 7	8	9	
			, {8, -2, -2, 4}, {1997, 3, 1, 3}, {1997, 3, 0, 3}// 10	11	12	
			, {8, -2, -3, 4}, {9, -2, -4, 4}, {7, -1, -4, 4}// 13	14	15	
			, {7, 0, -4, 4}, {8, -2, 1, 4}, {1997, 3, -1, 3}// 16	17	18	
			, {1997, 3, -2, 3}, {1997, 3, -3, 3}, {8, -2, 0, 4}// 19	20	21	
			, {8, -2, -1, 4}, {7, 1, -4, 4}, {7, 2, -4, 4}// 22	23	24	
			, {7, 3, -4, 4}, {1997, 2, 1, 3}, {1997, 2, 0, 3}// 25	26	27	
			, {1997, 2, -1, 3}, {1997, 2, -2, 3}, {1997, 2, -3, 3}// 28	29	30	
			, {1997, 1, 1, 3}, {1997, 1, 0, 3}, {1997, 1, -1, 3}// 31	32	33	
			, {1997, 1, -2, 3}, {1997, 1, -3, 3}, {1997, 0, -2, 3}// 34	35	36	
			, {1997, 0, -3, 3}, {1997, 0, 1, 3}, {1997, 0, 0, 3}// 37	38	39	
			, {1997, 0, -1, 3}, {1997, -1, 1, 3}, {1997, -1, 0, 3}// 40	41	42	
			, {1997, -1, -1, 3}, {1997, -1, -2, 3}, {1997, -1, -3, 3}// 43	44	45	
			, {13422, -1, -2, 4}, {6055, 1, 1, 4}, {13422, 0, -2, 4}// 46	47	48	
			, {13422, 0, -1, 4}, {6060, -1, -3, 4}, {13422, 0, 0, 4}// 49	50	51	
			, {6049, -1, 1, 4}, {13422, -1, 0, 4}, {6050, 0, 1, 4}// 52	53	54	
			, {6046, 1, 0, 4}, {6046, 1, -1, 4}, {6046, 1, -3, 4}// 55	56	57	
			, {6045, 1, -2, 4}, {8099, 0, -2, 5}, {8109, 0, -1, 5}// 58	59	60	
			, {8114, 0, 0, 5}, {2317, -1, -1, 0}, {3118, -1, -1, 5}// 61	62	64	
			, {3118, -1, 0, 12}, {3120, -1, -2, 5}, {3117, 1, -1, 4}// 65	66	67	
			, {7605, 0, 0, 5}, {7606, 1, 1, 4}, {7604, 1, 0, 4}// 68	69	70	
			, {3089, -1, -3, 4}, {2213, 1, -3, 4}, {8, 3, 3, 4}// 71	72	73	
			, {8, 3, 2, 4}, {8, -2, 4, 4}, {8, -2, 3, 4}// 74	75	76	
			, {8, -2, 2, 4}, {1997, 3, 4, 3}, {1997, 3, 3, 3}// 77	78	79	
			, {1997, 3, 2, 3}, {1997, 2, 4, 3}, {1997, 2, 3, 3}// 80	81	82	
			, {1997, 2, 2, 3}, {6, 3, 4, 4}, {7, 2, 4, 4}// 83	84	85	
			, {7, 1, 4, 4}, {7, 0, 4, 4}, {7, -1, 4, 4}// 86	87	88	
			, {1997, 1, 4, 3}, {1997, 1, 3, 3}, {1997, 1, 2, 3}// 89	90	91	
			, {1997, 0, 4, 3}, {1997, -1, 4, 3}, {1997, -1, 3, 3}// 92	93	94	
			, {1997, -1, 2, 3}, {1997, 0, 3, 3}, {1997, 0, 2, 3}// 95	96	97	
			, {4014, -1, 2, 4}// 98	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new ShipAddonDeed();
			}
		}

		[ Constructable ]
		public ShipAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 3748, -1, -1, 2, 1, -1, "", 1);// 63

		}

		public ShipAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class ShipAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new ShipAddon();
			}
		}

		[Constructable]
		public ShipAddonDeed()
		{
			Name = "Ship";
		}

		public ShipAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}