/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class casitapiedra2Addon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new casitapiedra2AddonDeed();
			}
		}

		[ Constructable ]
		public casitapiedra2Addon()
		{
			AddonComponent ac = null;
			ac = new AddonComponent( 1306 );
			AddComponent( ac, -5, -3, 0 );
			ac = new AddonComponent( 1306 );
			AddComponent( ac, -5, -2, 0 );
			ac = new AddonComponent( 1306 );
			AddComponent( ac, -5, -1, 0 );
			ac = new AddonComponent( 1306 );
			AddComponent( ac, -5, 0, 0 );
			ac = new AddonComponent( 1306 );
			AddComponent( ac, -5, 1, 0 );
			ac = new AddonComponent( 1306 );
			AddComponent( ac, -5, 2, 0 );
			ac = new AddonComponent( 201 );
			AddComponent( ac, -5, -3, 0 );
			ac = new AddonComponent( 201 );
			AddComponent( ac, -5, -2, 0 );
			ac = new AddonComponent( 201 );
			AddComponent( ac, -5, -1, 0 );
			ac = new AddonComponent( 201 );
			AddComponent( ac, -5, 0, 0 );
			ac = new AddonComponent( 201 );
			AddComponent( ac, -5, 1, 0 );
			ac = new AddonComponent( 201 );
			AddComponent( ac, -5, 2, 0 );
			ac = new AddonComponent( 200 );
			AddComponent( ac, -4, -4, 0 );
			ac = new AddonComponent( 200 );
			AddComponent( ac, -3, -4, 0 );
			ac = new AddonComponent( 1306 );
			AddComponent( ac, -4, -3, 0 );
			ac = new AddonComponent( 1306 );
			AddComponent( ac, -4, -2, 0 );
			ac = new AddonComponent( 1306 );
			AddComponent( ac, -4, -1, 0 );
			ac = new AddonComponent( 1306 );
			AddComponent( ac, -4, 0, 0 );
			ac = new AddonComponent( 1306 );
			AddComponent( ac, -4, 1, 0 );
			ac = new AddonComponent( 1306 );
			AddComponent( ac, -4, 2, 0 );
			ac = new AddonComponent( 1306 );
			AddComponent( ac, -3, -3, 0 );
			ac = new AddonComponent( 1306 );
			AddComponent( ac, -3, -2, 0 );
			ac = new AddonComponent( 1306 );
			AddComponent( ac, -3, -1, 0 );
			ac = new AddonComponent( 1306 );
			AddComponent( ac, -3, 0, 0 );
			ac = new AddonComponent( 1306 );
			AddComponent( ac, -3, 1, 0 );
			ac = new AddonComponent( 1306 );
			AddComponent( ac, -3, 2, 0 );
			ac = new AddonComponent( 221 );
			AddComponent( ac, -5, -3, 20 );
			ac = new AddonComponent( 221 );
			AddComponent( ac, -5, -2, 20 );
			ac = new AddonComponent( 221 );
			AddComponent( ac, -5, -1, 20 );
			ac = new AddonComponent( 221 );
			AddComponent( ac, -5, 0, 20 );
			ac = new AddonComponent( 221 );
			AddComponent( ac, -5, 1, 20 );
			ac = new AddonComponent( 221 );
			AddComponent( ac, -5, 2, 20 );
			ac = new AddonComponent( 222 );
			AddComponent( ac, -4, -4, 20 );
			ac = new AddonComponent( 222 );
			AddComponent( ac, -3, -4, 20 );
			ac = new AddonComponent( 1597 );
			AddComponent( ac, -4, -3, 20 );
			ac = new AddonComponent( 1597 );
			AddComponent( ac, -4, -2, 20 );
			ac = new AddonComponent( 1597 );
			AddComponent( ac, -4, -1, 20 );
			ac = new AddonComponent( 1597 );
			AddComponent( ac, -4, 0, 20 );
			ac = new AddonComponent( 1597 );
			AddComponent( ac, -4, 1, 20 );
			ac = new AddonComponent( 1597 );
			AddComponent( ac, -4, 2, 20 );
			ac = new AddonComponent( 1597 );
			AddComponent( ac, -3, -3, 20 );
			ac = new AddonComponent( 1597 );
			AddComponent( ac, -3, -2, 20 );
			ac = new AddonComponent( 1597 );
			AddComponent( ac, -3, -1, 20 );
			ac = new AddonComponent( 1597 );
			AddComponent( ac, -3, 0, 20 );
			ac = new AddonComponent( 1597 );
			AddComponent( ac, -3, 1, 20 );
			ac = new AddonComponent( 1597 );
			AddComponent( ac, -3, 2, 20 );
			ac = new AddonComponent( 1306 );
			AddComponent( ac, -5, 3, 0 );
			ac = new AddonComponent( 201 );
			AddComponent( ac, -5, 3, 0 );
			ac = new AddonComponent( 201 );
			AddComponent( ac, -5, 4, 0 );
			ac = new AddonComponent( 1306 );
			AddComponent( ac, -4, 3, 0 );
			ac = new AddonComponent( 1306 );
			AddComponent( ac, -4, 4, 0 );
			ac = new AddonComponent( 1306 );
			AddComponent( ac, -3, 3, 0 );
			ac = new AddonComponent( 1306 );
			AddComponent( ac, -3, 4, 0 );
			ac = new AddonComponent( 200 );
			AddComponent( ac, -4, 4, 0 );
			ac = new AddonComponent( 200 );
			AddComponent( ac, -3, 4, 0 );
			ac = new AddonComponent( 211 );
			AddComponent( ac, -4, 5, 0 );
			ac = new AddonComponent( 221 );
			AddComponent( ac, -5, 3, 20 );
			ac = new AddonComponent( 221 );
			AddComponent( ac, -5, 4, 20 );
			ac = new AddonComponent( 1597 );
			AddComponent( ac, -4, 3, 20 );
			ac = new AddonComponent( 1597 );
			AddComponent( ac, -4, 4, 20 );
			ac = new AddonComponent( 1597 );
			AddComponent( ac, -3, 3, 20 );
			ac = new AddonComponent( 1597 );
			AddComponent( ac, -3, 4, 20 );
			ac = new AddonComponent( 222 );
			AddComponent( ac, -4, 4, 20 );
			ac = new AddonComponent( 222 );
			AddComponent( ac, -3, 4, 20 );
			ac = new AddonComponent( 200 );
			AddComponent( ac, -2, -4, 0 );
			ac = new AddonComponent( 200 );
			AddComponent( ac, -1, -4, 0 );
			ac = new AddonComponent( 200 );
			AddComponent( ac, 0, -4, 0 );
			ac = new AddonComponent( 1306 );
			AddComponent( ac, -2, -3, 0 );
			ac = new AddonComponent( 1306 );
			AddComponent( ac, -2, -2, 0 );
			ac = new AddonComponent( 1306 );
			AddComponent( ac, -2, -1, 0 );
			ac = new AddonComponent( 1306 );
			AddComponent( ac, -2, 0, 0 );
			ac = new AddonComponent( 1306 );
			AddComponent( ac, -2, 1, 0 );
			ac = new AddonComponent( 1306 );
			AddComponent( ac, -2, 2, 0 );
			ac = new AddonComponent( 1306 );
			AddComponent( ac, -1, -3, 0 );
			ac = new AddonComponent( 1306 );
			AddComponent( ac, -1, -2, 0 );
			ac = new AddonComponent( 1306 );
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 1306 );
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 1306 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 1306 );
			AddComponent( ac, -1, 2, 0 );
			ac = new AddonComponent( 1306 );
			AddComponent( ac, 0, -3, 0 );
			ac = new AddonComponent( 1306 );
			AddComponent( ac, 0, -2, 0 );
			ac = new AddonComponent( 1306 );
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 1306 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 1306 );
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 1306 );
			AddComponent( ac, 0, 2, 0 );
			ac = new AddonComponent( 201 );
			AddComponent( ac, 0, -3, 0 );
			ac = new AddonComponent( 201 );
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 201 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 222 );
			AddComponent( ac, 1, -4, 0 );
			ac = new AddonComponent( 222 );
			AddComponent( ac, 2, -4, 0 );
			ac = new AddonComponent( 222 );
			AddComponent( ac, 3, -4, 0 );
			ac = new AddonComponent( 222 );
			AddComponent( ac, 4, -4, 0 );
			ac = new AddonComponent( 222 );
			AddComponent( ac, 5, -4, 0 );
			ac = new AddonComponent( 2123 );
			AddComponent( ac, 1, -4, 4 );
			ac = new AddonComponent( 2123 );
			AddComponent( ac, 2, -4, 4 );
			ac = new AddonComponent( 2123 );
			AddComponent( ac, 3, -4, 4 );
			ac = new AddonComponent( 2123 );
			AddComponent( ac, 4, -4, 4 );
			ac = new AddonComponent( 2123 );
			AddComponent( ac, 5, -4, 4 );
			ac = new AddonComponent( 1181 );
			AddComponent( ac, 1, -3, 0 );
			ac = new AddonComponent( 1181 );
			AddComponent( ac, 1, -2, 0 );
			ac = new AddonComponent( 1181 );
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 1181 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 1181 );
			AddComponent( ac, 2, -3, 0 );
			ac = new AddonComponent( 1181 );
			AddComponent( ac, 2, -2, 0 );
			ac = new AddonComponent( 1181 );
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 1181 );
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 1181 );
			AddComponent( ac, 3, -3, 0 );
			ac = new AddonComponent( 1181 );
			AddComponent( ac, 3, -2, 0 );
			ac = new AddonComponent( 1181 );
			AddComponent( ac, 3, -1, 0 );
			ac = new AddonComponent( 1181 );
			AddComponent( ac, 3, 0, 0 );
			ac = new AddonComponent( 1181 );
			AddComponent( ac, 4, -3, 0 );
			ac = new AddonComponent( 1181 );
			AddComponent( ac, 4, -2, 0 );
			ac = new AddonComponent( 1181 );
			AddComponent( ac, 4, -1, 0 );
			ac = new AddonComponent( 1181 );
			AddComponent( ac, 4, 0, 0 );
			ac = new AddonComponent( 1181 );
			AddComponent( ac, 5, -3, 0 );
			ac = new AddonComponent( 1181 );
			AddComponent( ac, 5, -2, 0 );
			ac = new AddonComponent( 1181 );
			AddComponent( ac, 5, -1, 0 );
			ac = new AddonComponent( 1181 );
			AddComponent( ac, 5, 0, 0 );
			ac = new AddonComponent( 1306 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 1306 );
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 1306 );
			AddComponent( ac, 1, 2, 0 );
			ac = new AddonComponent( 1306 );
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 1306 );
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 1306 );
			AddComponent( ac, 2, 2, 0 );
			ac = new AddonComponent( 1306 );
			AddComponent( ac, 3, 0, 0 );
			ac = new AddonComponent( 1306 );
			AddComponent( ac, 3, 1, 0 );
			ac = new AddonComponent( 1306 );
			AddComponent( ac, 3, 2, 0 );
			ac = new AddonComponent( 1306 );
			AddComponent( ac, 4, 0, 0 );
			ac = new AddonComponent( 1306 );
			AddComponent( ac, 4, 1, 0 );
			ac = new AddonComponent( 1306 );
			AddComponent( ac, 4, 2, 0 );
			ac = new AddonComponent( 200 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 200 );
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 200 );
			AddComponent( ac, 3, 0, 0 );
			ac = new AddonComponent( 200 );
			AddComponent( ac, 4, 0, 0 );
			ac = new AddonComponent( 200 );
			AddComponent( ac, 5, 0, 0 );
			ac = new AddonComponent( 2208 );
			AddComponent( ac, 1, 1, 12 );
			ac = new AddonComponent( 2209 );
			AddComponent( ac, 2, 1, 1 );
			ac = new AddonComponent( 221 );
			AddComponent( ac, 5, -3, 0 );
			ac = new AddonComponent( 221 );
			AddComponent( ac, 5, -2, 0 );
			ac = new AddonComponent( 221 );
			AddComponent( ac, 5, -1, 0 );
			ac = new AddonComponent( 221 );
			AddComponent( ac, 5, 0, 0 );
			ac = new AddonComponent( 2121 );
			AddComponent( ac, 5, -3, 5 );
			ac = new AddonComponent( 2121 );
			AddComponent( ac, 5, -2, 4 );
			ac = new AddonComponent( 2121 );
			AddComponent( ac, 5, -1, 4 );
			ac = new AddonComponent( 2121 );
			AddComponent( ac, 5, 0, 4 );
			ac = new AddonComponent( 1306 );
			AddComponent( ac, 5, 1, 0 );
			ac = new AddonComponent( 1306 );
			AddComponent( ac, 5, 2, 0 );
			ac = new AddonComponent( 201 );
			AddComponent( ac, 5, 1, 0 );
			ac = new AddonComponent( 201 );
			AddComponent( ac, 5, 2, 0 );
			ac = new AddonComponent( 210 );
			AddComponent( ac, 6, 1, 0 );
			ac = new AddonComponent( 222 );
			AddComponent( ac, -2, -4, 20 );
			ac = new AddonComponent( 222 );
			AddComponent( ac, -1, -4, 20 );
			ac = new AddonComponent( 222 );
			AddComponent( ac, 0, -4, 20 );
			ac = new AddonComponent( 1597 );
			AddComponent( ac, -2, -3, 20 );
			ac = new AddonComponent( 1597 );
			AddComponent( ac, -2, -2, 20 );
			ac = new AddonComponent( 1597 );
			AddComponent( ac, -2, -1, 20 );
			ac = new AddonComponent( 1597 );
			AddComponent( ac, -2, 0, 20 );
			ac = new AddonComponent( 1597 );
			AddComponent( ac, -2, 1, 20 );
			ac = new AddonComponent( 1597 );
			AddComponent( ac, -2, 2, 20 );
			ac = new AddonComponent( 1597 );
			AddComponent( ac, -1, -3, 20 );
			ac = new AddonComponent( 1597 );
			AddComponent( ac, -1, -2, 20 );
			ac = new AddonComponent( 1597 );
			AddComponent( ac, -1, -1, 20 );
			ac = new AddonComponent( 1597 );
			AddComponent( ac, -1, 0, 20 );
			ac = new AddonComponent( 1597 );
			AddComponent( ac, -1, 1, 20 );
			ac = new AddonComponent( 1597 );
			AddComponent( ac, -1, 2, 20 );
			ac = new AddonComponent( 1597 );
			AddComponent( ac, 0, -3, 20 );
			ac = new AddonComponent( 1597 );
			AddComponent( ac, 0, -2, 20 );
			ac = new AddonComponent( 1597 );
			AddComponent( ac, 0, -1, 20 );
			ac = new AddonComponent( 1597 );
			AddComponent( ac, 0, 0, 20 );
			ac = new AddonComponent( 1597 );
			AddComponent( ac, 0, 1, 20 );
			ac = new AddonComponent( 1597 );
			AddComponent( ac, 0, 2, 20 );
			ac = new AddonComponent( 221 );
			AddComponent( ac, 0, -3, 20 );
			ac = new AddonComponent( 221 );
			AddComponent( ac, 0, -2, 20 );
			ac = new AddonComponent( 221 );
			AddComponent( ac, 0, -1, 20 );
			ac = new AddonComponent( 221 );
			AddComponent( ac, 0, 0, 20 );
			ac = new AddonComponent( 222 );
			AddComponent( ac, 1, 0, 20 );
			ac = new AddonComponent( 222 );
			AddComponent( ac, 2, 0, 20 );
			ac = new AddonComponent( 222 );
			AddComponent( ac, 3, 0, 20 );
			ac = new AddonComponent( 222 );
			AddComponent( ac, 4, 0, 20 );
			ac = new AddonComponent( 222 );
			AddComponent( ac, 5, 0, 20 );
			ac = new AddonComponent( 1597 );
			AddComponent( ac, 1, 2, 20 );
			ac = new AddonComponent( 1597 );
			AddComponent( ac, 2, 2, 20 );
			ac = new AddonComponent( 1597 );
			AddComponent( ac, 3, 1, 20 );
			ac = new AddonComponent( 1597 );
			AddComponent( ac, 3, 2, 20 );
			ac = new AddonComponent( 1597 );
			AddComponent( ac, 4, 1, 20 );
			ac = new AddonComponent( 1597 );
			AddComponent( ac, 4, 2, 20 );
			ac = new AddonComponent( 1597 );
			AddComponent( ac, 5, 1, 20 );
			ac = new AddonComponent( 1597 );
			AddComponent( ac, 5, 2, 20 );
			ac = new AddonComponent( 221 );
			AddComponent( ac, 5, 1, 20 );
			ac = new AddonComponent( 221 );
			AddComponent( ac, 5, 2, 20 );
			ac = new AddonComponent( 1306 );
			AddComponent( ac, -2, 3, 0 );
			ac = new AddonComponent( 1306 );
			AddComponent( ac, -2, 4, 0 );
			ac = new AddonComponent( 1306 );
			AddComponent( ac, -1, 3, 0 );
			ac = new AddonComponent( 1306 );
			AddComponent( ac, -1, 4, 0 );
			ac = new AddonComponent( 1306 );
			AddComponent( ac, 0, 3, 0 );
			ac = new AddonComponent( 1306 );
			AddComponent( ac, 0, 4, 0 );
			ac = new AddonComponent( 202 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, -2, 4, 0 );
			ac = new AddonComponent( 200 );
			AddComponent( ac, -1, 4, 0 );
			ac = new AddonComponent( 1306 );
			AddComponent( ac, 1, 3, 0 );
			ac = new AddonComponent( 1306 );
			AddComponent( ac, 1, 4, 0 );
			ac = new AddonComponent( 1306 );
			AddComponent( ac, 2, 3, 0 );
			ac = new AddonComponent( 1306 );
			AddComponent( ac, 2, 4, 0 );
			ac = new AddonComponent( 1306 );
			AddComponent( ac, 3, 3, 0 );
			ac = new AddonComponent( 1306 );
			AddComponent( ac, 3, 4, 0 );
			ac = new AddonComponent( 1306 );
			AddComponent( ac, 4, 3, 0 );
			ac = new AddonComponent( 1306 );
			AddComponent( ac, 4, 4, 0 );
			ac = new AddonComponent( 200 );
			AddComponent( ac, 1, 4, 0 );
			ac = new AddonComponent( 202 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 2, 4, 0 );
			ac = new AddonComponent( 200 );
			AddComponent( ac, 3, 4, 0 );
			ac = new AddonComponent( 200 );
			AddComponent( ac, 4, 4, 0 );
			ac = new AddonComponent( 211 );
			AddComponent( ac, 4, 5, 0 );
			ac = new AddonComponent( 1306 );
			AddComponent( ac, 5, 3, 0 );
			ac = new AddonComponent( 1306 );
			AddComponent( ac, 5, 4, 0 );
			ac = new AddonComponent( 201 );
			AddComponent( ac, 5, 3, 0 );
			ac = new AddonComponent( 199 );
			AddComponent( ac, 5, 4, 0 );
			ac = new AddonComponent( 210 );
			AddComponent( ac, 6, 3, 0 );
			ac = new AddonComponent( 1597 );
			AddComponent( ac, -2, 3, 20 );
			ac = new AddonComponent( 1597 );
			AddComponent( ac, -2, 4, 20 );
			ac = new AddonComponent( 1597 );
			AddComponent( ac, -1, 3, 20 );
			ac = new AddonComponent( 1597 );
			AddComponent( ac, -1, 4, 20 );
			ac = new AddonComponent( 1597 );
			AddComponent( ac, 0, 3, 20 );
			ac = new AddonComponent( 1597 );
			AddComponent( ac, 0, 4, 20 );
			ac = new AddonComponent( 222 );
			AddComponent( ac, -2, 4, 20 );
			ac = new AddonComponent( 222 );
			AddComponent( ac, -1, 4, 20 );
			ac = new AddonComponent( 222 );
			AddComponent( ac, 0, 4, 20 );
			ac = new AddonComponent( 222 );
			AddComponent( ac, 1, 4, 20 );
			ac = new AddonComponent( 222 );
			AddComponent( ac, 2, 4, 20 );
			ac = new AddonComponent( 222 );
			AddComponent( ac, 3, 4, 20 );
			ac = new AddonComponent( 222 );
			AddComponent( ac, 4, 4, 20 );
			ac = new AddonComponent( 222 );
			AddComponent( ac, 5, 4, 20 );
			ac = new AddonComponent( 1597 );
			AddComponent( ac, 1, 3, 20 );
			ac = new AddonComponent( 1597 );
			AddComponent( ac, 1, 4, 20 );
			ac = new AddonComponent( 1597 );
			AddComponent( ac, 2, 3, 20 );
			ac = new AddonComponent( 1597 );
			AddComponent( ac, 2, 4, 20 );
			ac = new AddonComponent( 1597 );
			AddComponent( ac, 3, 3, 20 );
			ac = new AddonComponent( 1597 );
			AddComponent( ac, 3, 4, 20 );
			ac = new AddonComponent( 1597 );
			AddComponent( ac, 4, 3, 20 );
			ac = new AddonComponent( 1597 );
			AddComponent( ac, 4, 4, 20 );
			ac = new AddonComponent( 1597 );
			AddComponent( ac, 5, 3, 20 );
			ac = new AddonComponent( 1597 );
			AddComponent( ac, 5, 4, 20 );
			ac = new AddonComponent( 221 );
			AddComponent( ac, 5, 3, 20 );
			ac = new AddonComponent( 221 );
			AddComponent( ac, 5, 4, 20 );

		}

		public casitapiedra2Addon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class casitapiedra2AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new casitapiedra2Addon();
			}
		}

		[Constructable]
		public casitapiedra2AddonDeed()
		{
			Name = "casitapiedra2";
		}

		public casitapiedra2AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}