/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class tiendacasaAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new tiendacasaAddonDeed();
			}
		}

		[ Constructable ]
		public tiendacasaAddon()
		{
			AddonComponent ac = null;
			ac = new AddonComponent( 167 );
			AddComponent( ac, -5, -1, 0 );
			ac = new AddonComponent( 167 );
			AddComponent( ac, -5, 0, 0 );
			ac = new AddonComponent( 1542 );
			AddComponent( ac, -5, -1, 1 );
			ac = new AddonComponent( 185 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, -5, 1, 0 );
			ac = new AddonComponent( 167 );
			AddComponent( ac, -5, 2, 0 );
			ac = new AddonComponent( 167 );
			AddComponent( ac, -5, 3, 0 );
			ac = new AddonComponent( 168 );
			AddComponent( ac, -4, -2, 0 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, -4, -1, 0 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, -4, 0, 0 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, -4, 1, 0 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, -4, 2, 0 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, -4, 3, 0 );
			ac = new AddonComponent( 1542 );
			AddComponent( ac, -4, -1, 16 );
			ac = new AddonComponent( 1535 );
			AddComponent( ac, -4, 0, 16 );
			ac = new AddonComponent( 1535 );
			AddComponent( ac, -4, 1, 16 );
			ac = new AddonComponent( 1535 );
			AddComponent( ac, -4, 2, 16 );
			ac = new AddonComponent( 168 );
			AddComponent( ac, -4, 3, 0 );
			ac = new AddonComponent( 1543 );
			AddComponent( ac, -4, 3, 16 );
			ac = new AddonComponent( 168 );
			AddComponent( ac, -3, -2, 0 );
			ac = new AddonComponent( 168 );
			AddComponent( ac, -2, -2, 0 );
			ac = new AddonComponent( 168 );
			AddComponent( ac, -1, -2, 0 );
			ac = new AddonComponent( 168 );
			AddComponent( ac, 0, -2, 0 );
			ac = new AddonComponent( 168 );
			AddComponent( ac, 1, -2, 0 );
			ac = new AddonComponent( 168 );
			AddComponent( ac, 2, -2, 0 );
			ac = new AddonComponent( 168 );
			AddComponent( ac, 3, -2, 0 );
			ac = new AddonComponent( 168 );
			AddComponent( ac, 4, -2, 0 );
			ac = new AddonComponent( 168 );
			AddComponent( ac, 5, -2, 0 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, -3, -1, 0 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, -3, 0, 0 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, -3, 1, 0 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, -3, 2, 0 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, -3, 3, 0 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, -2, -1, 0 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, -2, 0, 0 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, -2, 1, 0 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, -2, 2, 0 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, -2, 3, 0 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, -1, 2, 0 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, -1, 3, 0 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 0, 2, 0 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 0, 3, 0 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 1, 2, 0 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 1, 3, 0 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 2, 2, 0 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 2, 3, 0 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 3, -1, 0 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 3, 0, 0 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 3, 1, 0 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 3, 2, 0 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 3, 3, 0 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 4, -1, 0 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 4, 0, 0 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 4, 1, 0 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 4, 2, 0 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 4, 3, 0 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 5, -1, 0 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 5, 0, 0 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 5, 1, 0 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 5, 2, 0 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 5, 3, 0 );
			ac = new AddonComponent( 1536 );
			AddComponent( ac, -3, -1, 16 );
			ac = new AddonComponent( 1536 );
			AddComponent( ac, -2, -1, 16 );
			ac = new AddonComponent( 1536 );
			AddComponent( ac, -1, -1, 16 );
			ac = new AddonComponent( 1536 );
			AddComponent( ac, 0, -1, 16 );
			ac = new AddonComponent( 1536 );
			AddComponent( ac, 1, -1, 16 );
			ac = new AddonComponent( 1536 );
			AddComponent( ac, 2, -1, 16 );
			ac = new AddonComponent( 1536 );
			AddComponent( ac, 3, -1, 16 );
			ac = new AddonComponent( 1536 );
			AddComponent( ac, 4, -1, 16 );
			ac = new AddonComponent( 1542 );
			AddComponent( ac, -3, 0, 0 );
			ac = new AddonComponent( 1542 );
			AddComponent( ac, -3, 0, 19 );
			ac = new AddonComponent( 1535 );
			AddComponent( ac, -3, 1, 19 );
			ac = new AddonComponent( 1543 );
			AddComponent( ac, -3, 2, 19 );
			ac = new AddonComponent( 186 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, -3, 3, 0 );
			ac = new AddonComponent( 1537 );
			AddComponent( ac, -3, 3, 16 );
			ac = new AddonComponent( 1537 );
			AddComponent( ac, -2, 3, 16 );
			ac = new AddonComponent( 1537 );
			AddComponent( ac, -1, 3, 16 );
			ac = new AddonComponent( 1537 );
			AddComponent( ac, 0, 3, 16 );
			ac = new AddonComponent( 1537 );
			AddComponent( ac, 1, 3, 16 );
			ac = new AddonComponent( 1537 );
			AddComponent( ac, 2, 3, 16 );
			ac = new AddonComponent( 1537 );
			AddComponent( ac, 3, 3, 16 );
			ac = new AddonComponent( 1537 );
			AddComponent( ac, 4, 3, 16 );
			ac = new AddonComponent( 1536 );
			AddComponent( ac, -2, 0, 19 );
			ac = new AddonComponent( 1536 );
			AddComponent( ac, -1, 0, 19 );
			ac = new AddonComponent( 1536 );
			AddComponent( ac, 0, 0, 19 );
			ac = new AddonComponent( 1536 );
			AddComponent( ac, 1, 0, 19 );
			ac = new AddonComponent( 1536 );
			AddComponent( ac, 2, 0, 19 );
			ac = new AddonComponent( 1536 );
			AddComponent( ac, 3, 0, 19 );
			ac = new AddonComponent( 1537 );
			AddComponent( ac, -2, 2, 19 );
			ac = new AddonComponent( 1537 );
			AddComponent( ac, -1, 2, 19 );
			ac = new AddonComponent( 1537 );
			AddComponent( ac, 0, 2, 19 );
			ac = new AddonComponent( 1537 );
			AddComponent( ac, 1, 2, 19 );
			ac = new AddonComponent( 1537 );
			AddComponent( ac, 2, 2, 19 );
			ac = new AddonComponent( 1537 );
			AddComponent( ac, 3, 2, 19 );
			ac = new AddonComponent( 168 );
			AddComponent( ac, -2, 3, 0 );
			ac = new AddonComponent( 168 );
			AddComponent( ac, -1, 3, 0 );
			ac = new AddonComponent( 168 );
			AddComponent( ac, 1, 3, 0 );
			ac = new AddonComponent( 168 );
			AddComponent( ac, 2, 3, 0 );
			ac = new AddonComponent( 186 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 3, 3, 0 );
			ac = new AddonComponent( 1538 );
			AddComponent( ac, 4, 1, 19 );
			ac = new AddonComponent( 168 );
			AddComponent( ac, 4, 3, 0 );
			ac = new AddonComponent( 167 );
			AddComponent( ac, 5, -1, 0 );
			ac = new AddonComponent( 167 );
			AddComponent( ac, 5, 0, 0 );
			ac = new AddonComponent( 1541 );
			AddComponent( ac, 5, -1, 16 );
			ac = new AddonComponent( 1538 );
			AddComponent( ac, 5, 0, 16 );
			ac = new AddonComponent( 1538 );
			AddComponent( ac, 5, 1, 16 );
			ac = new AddonComponent( 1538 );
			AddComponent( ac, 5, 2, 16 );
			ac = new AddonComponent( 185 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 5, 1, 0 );
			ac = new AddonComponent( 167 );
			AddComponent( ac, 5, 2, 0 );
			ac = new AddonComponent( 1538 );
			AddComponent( ac, 5, 2, 16 );
			ac = new AddonComponent( 166 );
			AddComponent( ac, 5, 3, 0 );
			ac = new AddonComponent( 1540 );
			AddComponent( ac, 5, 3, 16 );
			ac = new AddonComponent( 1546 );
			AddComponent( ac, -2, 1, 22 );
			ac = new AddonComponent( 1539 );
			AddComponent( ac, -1, 1, 22 );
			ac = new AddonComponent( 1539 );
			AddComponent( ac, 0, 1, 22 );
			ac = new AddonComponent( 1539 );
			AddComponent( ac, 1, 1, 22 );
			ac = new AddonComponent( 1539 );
			AddComponent( ac, 2, 1, 22 );
			ac = new AddonComponent( 1545 );
			AddComponent( ac, 3, 1, 22 );
			ac = new AddonComponent( 1541 );
			AddComponent( ac, 5, 1, 30 );
			ac = new AddonComponent( 1540 );
			AddComponent( ac, 5, 3, 30 );

		}

		public tiendacasaAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class tiendacasaAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new tiendacasaAddon();
			}
		}

		[Constructable]
		public tiendacasaAddonDeed()
		{
			Name = "tiendacasa";
		}

		public tiendacasaAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}