/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Addons
{
	public class BallistaSouthAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new BallistaSouthAddonDeed();
			}
		}

		[ Constructable ]
		public BallistaSouthAddon()
		{
			AddComponent( new AddonComponent( 16263 ), -2, 0, 0 );
			AddComponent( new AddonComponent( 16249 ), 1, -1, 0 );
			AddComponent( new AddonComponent( 16257 ), 1, 0, 0 );
			AddComponent( new AddonComponent( 16265 ), 1, 1, 0 );
			AddComponent( new AddonComponent( 16230 ), 1, 2, 0 );
			AddComponent( new AddonComponent( 16253 ), -1, -1, 0 );
			AddComponent( new AddonComponent( 16261 ), -1, 0, 0 );
			AddComponent( new AddonComponent( 16259 ), 0, 0, 0 );
			AddComponent( new AddonComponent( 16251 ), 0, -1, 0 );
			AddComponent( new AddonComponent( 16270 ), 0, 2, 0 );
			AddComponent( new AddonComponent( 16267 ), 0, 1, 0 );
			AddComponent( new AddonComponent( 16269 ), -1, 1, 0 );
			AddComponent( new AddonComponent( 16235 ), -1, 2, 0 );
			AddComponent( new AddonComponent( 16247 ), 0, -2, 0 );
			AddComponent( new AddonComponent( 16255 ), 2, 0, 0 );
		}

		public BallistaSouthAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class BallistaSouthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new BallistaSouthAddon();
			}
		}

		[Constructable]
		public BallistaSouthAddonDeed()
		{
			Name = "BallistaSouth";
		}

		public BallistaSouthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}