/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Addons
{
	public class CatapultEastAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new CatapultEastAddonDeed();
			}
		}

		[ Constructable ]
		public CatapultEastAddon()
		{
			AddComponent( new AddonComponent( 5749 ), -1, -1, 0 );
			AddComponent( new AddonComponent( 5750 ), -1, 0, 0 );
			AddComponent( new AddonComponent( 5752 ), 0, 0, 0 );
			AddComponent( new AddonComponent( 5753 ), 2, 1, 0 );
			AddComponent( new AddonComponent( 5773 ), 2, 1, 0 );
			AddComponent( new AddonComponent( 5746 ), 2, 0, 0 );
			AddComponent( new AddonComponent( 5768 ), 2, -1, 0 );
			AddComponent( new AddonComponent( 5751 ), -1, 1, 0 );
			AddComponent( new AddonComponent( 5747 ), 1, 1, 0 );
			AddComponent( new AddonComponent( 5758 ), 0, 1, 0 );
			AddComponent( new AddonComponent( 5748 ), 1, -1, 0 );
			AddComponent( new AddonComponent( 5763 ), 0, -1, 0 );
		}

		public CatapultEastAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class CatapultEastAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new CatapultEastAddon();
			}
		}

		[Constructable]
		public CatapultEastAddonDeed()
		{
			Name = "CatapultEast";
		}

		public CatapultEastAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}