
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class BuffetTableN2SAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {40264, 1, 2, 0}, {40263, 0, 2, 0}, {40262, 1, 1, 0}// 1	2	3	
			, {40261, 0, 1, 0}, {40260, 1, 0, 0}, {40259, 0, 0, 0}// 4	5	6	
			, {40258, 1, -1, 0}, {40257, 0, -1, 0}, {40256, 1, -2, 0}// 7	8	9	
			, {40255, 0, -2, 0}// 10	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new BuffetTableN2SAddonDeed();
			}
		}

		[ Constructable ]
		public BuffetTableN2SAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public BuffetTableN2SAddon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class BuffetTableN2SAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new BuffetTableN2SAddon();
			}
		}

		[Constructable]
		public BuffetTableN2SAddonDeed()
		{
			Name = "Buffet Table N2S";
		}

		public BuffetTableN2SAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}