
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class RoseArborAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {2919, -3, -1, 0}, {2919, 0, -1, 0}, {2919, -2, -1, 0}// 42	43	44	
			, {2919, -1, -1, 0}// 50	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new RoseArborAddonDeed();
			}
		}

		[ Constructable ]
		public RoseArborAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 10806, 1, -1, 0, 1055, -1, "Rose Arbor", 1);// 1
			AddComplexComponent( (BaseAddon) this, 39460, 1, 1, 36, 0, -1, "Rose Arbor", 1);// 2
			AddComplexComponent( (BaseAddon) this, 3565, -2, 0, 16, 1369, -1, "Rose Arbor", 1);// 3
			AddComplexComponent( (BaseAddon) this, 10808, -2, -1, 19, 1055, -1, "Rose Arbor", 1);// 4
			AddComplexComponent( (BaseAddon) this, 39460, -2, 0, 17, 0, -1, "Rose Arbor", 1);// 5
			AddComplexComponent( (BaseAddon) this, 3565, 2, 0, 2, 1369, -1, "Rose Arbor", 1);// 6
			AddComplexComponent( (BaseAddon) this, 39460, -2, 0, 5, 0, -1, "Rose Arbor", 1);// 7
			AddComplexComponent( (BaseAddon) this, 39458, -2, 0, 0, 0, -1, "Rose Arbor", 1);// 8
			AddComplexComponent( (BaseAddon) this, 39461, -1, 0, 28, 0, -1, "Rose Arbor", 1);// 9
			AddComplexComponent( (BaseAddon) this, 3564, 0, 0, 27, 1369, -1, "Rose Arbor", 1);// 10
			AddComplexComponent( (BaseAddon) this, 3565, -2, 0, 2, 1369, -1, "Rose Arbor", 1);// 11
			AddComplexComponent( (BaseAddon) this, 39460, 2, 1, 33, 0, -1, "Rose Arbor", 1);// 12
			AddComplexComponent( (BaseAddon) this, 6362, 0, 0, 33, 38, -1, "Rose Arbor", 1);// 13
			AddComplexComponent( (BaseAddon) this, 6361, 2, 1, 35, 38, -1, "Rose Arbor", 1);// 14
			AddComplexComponent( (BaseAddon) this, 3564, -1, 0, 25, 1369, -1, "Rose Arbor", 1);// 15
			AddComplexComponent( (BaseAddon) this, 39461, 3, 1, 39, 0, -1, "Rose Arbor", 1);// 16
			AddComplexComponent( (BaseAddon) this, 39458, 2, 0, 0, 0, -1, "Rose Arbor", 1);// 17
			AddComplexComponent( (BaseAddon) this, 414, 2, 0, 16, 1014, -1, "Rose Arbor", 1);// 18
			AddComplexComponent( (BaseAddon) this, 3565, 2, 0, 17, 1369, -1, "Rose Arbor", 1);// 19
			AddComplexComponent( (BaseAddon) this, 3168, 2, 1, 37, 0, -1, "Rose Arbor", 1);// 20
			AddComplexComponent( (BaseAddon) this, 3166, 0, 0, 30, 0, -1, "Rose Arbor", 1);// 21
			AddComplexComponent( (BaseAddon) this, 414, 1, 0, 16, 1014, -1, "Rose Arbor", 1);// 22
			AddComplexComponent( (BaseAddon) this, 6361, -2, 0, 8, 38, -1, "Rose Arbor", 1);// 23
			AddComplexComponent( (BaseAddon) this, 39460, 2, 0, 3, 0, -1, "Rose Arbor", 1);// 24
			AddComplexComponent( (BaseAddon) this, 39460, 2, 1, 20, 0, -1, "Rose Arbor", 1);// 25
			AddComplexComponent( (BaseAddon) this, 6361, 2, 0, 6, 38, -1, "Rose Arbor", 1);// 26
			AddComplexComponent( (BaseAddon) this, 6362, 2, 0, 26, 38, -1, "Rose Arbor", 1);// 27
			AddComplexComponent( (BaseAddon) this, 10806, -2, -1, 0, 1055, -1, "Rose Arbor", 1);// 28
			AddComplexComponent( (BaseAddon) this, 3167, -1, 0, 30, 0, -1, "Rose Arbor", 1);// 29
			AddComplexComponent( (BaseAddon) this, 3166, 0, 0, 26, 0, -1, "Rose Arbor", 1);// 30
			AddComplexComponent( (BaseAddon) this, 3564, 0, 0, 29, 1369, -1, "Rose Arbor", 1);// 31
			AddComplexComponent( (BaseAddon) this, 3564, 3, 1, 37, 1369, -1, "Rose Arbor", 1);// 32
			AddComplexComponent( (BaseAddon) this, 39460, 2, 0, 3, 0, -1, "Rose Arbor", 1);// 33
			AddComplexComponent( (BaseAddon) this, 414, 0, 0, 16, 1014, -1, "Rose Arbor", 1);// 34
			AddComplexComponent( (BaseAddon) this, 3564, 1, 0, 27, 1369, -1, "Rose Arbor", 1);// 35
			AddComplexComponent( (BaseAddon) this, 6361, 2, 1, 40, 38, -1, "Rose Arbor", 1);// 36
			AddComplexComponent( (BaseAddon) this, 39460, -2, 0, 24, 0, -1, "Rose Arbor", 1);// 37
			AddComplexComponent( (BaseAddon) this, 39460, -3, 0, 3, 0, -1, "Rose Arbor", 1);// 38
			AddComplexComponent( (BaseAddon) this, 39460, 3, 1, 31, 0, -1, "Rose Arbor", 1);// 39
			AddComplexComponent( (BaseAddon) this, 3167, 1, 0, 32, 0, -1, "Rose Arbor", 1);// 40
			AddComplexComponent( (BaseAddon) this, 39460, 1, 0, 28, 0, -1, "Rose Arbor", 1);// 41
			AddComplexComponent( (BaseAddon) this, 39460, 0, 0, 32, 0, -1, "Rose Arbor", 1);// 45
			AddComplexComponent( (BaseAddon) this, 6362, 1, 0, 33, 38, -1, "Rose Arbor", 1);// 46
			AddComplexComponent( (BaseAddon) this, 6362, 2, 0, 11, 38, -1, "Rose Arbor", 1);// 47
			AddComplexComponent( (BaseAddon) this, 6362, -1, 1, 14, 38, -1, "Rose Arbor", 1);// 48
			AddComplexComponent( (BaseAddon) this, 39460, 3, 1, 43, 0, -1, "Rose Arbor", 1);// 49

		}

		public RoseArborAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class RoseArborAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new RoseArborAddon();
			}
		}

		[Constructable]
		public RoseArborAddonDeed()
		{
			Name = "RoseArbor";
		}

		public RoseArborAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}