
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class ShipwreckNorth_Addon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {18352, 1, 1, 0}, {18356, 1, 3, 0}, {18330, 1, 2, 0}// 1	2	3	
			, {18333, 1, 2, 0}, {18332, 1, 2, 0}, {18331, 1, 2, 0}// 4	5	6	
			, {18336, 1, -1, 0}, {18342, 1, 0, 0}, {18335, 1, -2, 0}// 7	8	9	
			, {18334, 2, -2, 0}, {18347, 2, 0, 0}, {18348, 1, 1, 0}// 10	11	12	
			, {18355, -1, 1, 0}, {18357, -2, 1, 0}, {18354, -1, 2, 0}// 13	14	15	
			, {18353, 0, 2, 0}, {18346, 0, 3, 0}, {18339, 0, 3, 0}// 16	17	18	
			, {18351, -1, 2, 0}, {18350, -1, 1, 0}, {18349, 0, 1, 0}// 19	20	21	
			, {18345, 0, 3, 0}, {18344, -1, 0, 0}, {18343, 0, 0, 0}// 22	23	24	
			, {18341, -2, 0, 0}, {18340, -2, 0, 0}, {18338, -1, -1, 0}// 25	26	27	
			, {18337, 0, -1, 0}// 28	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new ShipwreckNorth_AddonDeed();
			}
		}

		[ Constructable ]
		public ShipwreckNorth_Addon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public ShipwreckNorth_Addon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class ShipwreckNorth_AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new ShipwreckNorth_Addon();
			}
		}

		[Constructable]
		public ShipwreckNorth_AddonDeed()
		{
			Name = "ShipwreckNorth_";
		}

		public ShipwreckNorth_AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}