/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class AGBloodyCouchNorthAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new AGBloodyCouchNorthAddonDeed();
			}
		}

		[ Constructable ]
		public AGBloodyCouchNorthAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 1848 );
			ac.Hue = 1109;
			ac.Name = "BloodyCoutch";
			AddComponent( ac, -2, 0, 0 );
			ac = new AddonComponent( 1848 );
			ac.Hue = 1109;
			ac.Name = "BloodyCoutch";
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 4634 );
			ac.Hue = 2106;
			ac.Name = "BloodyCoutch";
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 4634 );
			ac.Hue = 2106;
			ac.Name = "BloodyCoutch";
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 4634 );
			ac.Hue = 2106;
			ac.Name = "BloodyCoutch";
			AddComponent( ac, 1, 0, 0 );

		}

		public AGBloodyCouchNorthAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class AGBloodyCouchNorthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new AGBloodyCouchNorthAddon();
			}
		}

		[Constructable]
		public AGBloodyCouchNorthAddonDeed()
		{
			Name = "AG Bloody Couch North";
		}

		public AGBloodyCouchNorthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}