/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class AGBloodyCouchEastAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new AGBloodyCouchEastAddonDeed();
			}
		}

		[ Constructable ]
		public AGBloodyCouchEastAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 1848 );
			ac.Hue = 1109;
			ac.Name = "BloodyCoutch";
			AddComponent( ac, 0, -2, 0 );
			ac = new AddonComponent( 1848 );
			ac.Hue = 1109;
			ac.Name = "BloodyCoutch";
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 1848 );
			ac.Hue = 1109;
			ac.Name = "BloodyCoutch";
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 1848 );
			ac.Hue = 1109;
			ac.Name = "BloodyCoutch";
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 1848 );
			ac.Hue = 1109;
			ac.Name = "BloodyCoutch";
			AddComponent( ac, 0, 2, 0 );
			ac = new AddonComponent( 4650 );
			ac.Hue = 37;
			AddComponent( ac, 0, -2, 5 );
			ac = new AddonComponent( 4650 );
			ac.Hue = 37;
			AddComponent( ac, 0, 2, 5 );
			ac = new AddonComponent( 5168 );
			ac.Light = LightType.NorthBig;
			ac.Hue = 37;
			ac.Name = "BloodCandle";
			AddComponent( ac, 0, -2, 7 );
			ac = new AddonComponent( 5168 );
			ac.Light = LightType.NorthBig;
			ac.Hue = 37;
			ac.Name = "BloodCandle";
			AddComponent( ac, 0, 2, 7 );
			ac = new AddonComponent( 9432 );
			ac.Hue = 32;
			ac.Name = "BloodFilledVase";
			AddComponent( ac, 0, 0, 7 );
			ac = new AddonComponent( 4467 );
			ac.Hue = 1102;
			ac.Name = "GraveOfTammerAddept";
			AddComponent( ac, 0, 1, 7 );
			ac = new AddonComponent( 4467 );
			ac.Hue = 1102;
			ac.Name = "GraveOfHalk";
			AddComponent( ac, 0, -1, 7 );
			ac = new AddonComponent( 9035 );
			ac.Hue = 1919;
			ac.Name = "RoseOfTheDead";
			AddComponent( ac, 0, 0, 16 );

		}

		public AGBloodyCouchEastAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class AGBloodyCouchEastAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new AGBloodyCouchEastAddon();
			}
		}

		[Constructable]
		public AGBloodyCouchEastAddonDeed()
		{
			Name = "AG Bloody Couch East";
		}

		public AGBloodyCouchEastAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}