/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class casita_madera4Addon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new casita_madera4AddonDeed();
			}
		}

		[ Constructable ]
		public casita_madera4Addon()
		{
			AddonComponent ac = null;
			ac = new AddonComponent( 1189 );
			AddComponent( ac, -4, -3, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, -3, -3, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, -2, -3, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, -1, -3, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, 0, -3, 1 );
			ac = new AddonComponent( 167 );
			AddComponent( ac, -4, -2, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, -4, -1, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, -4, 0, 1 );
			ac = new AddonComponent( 185 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, -4, -1, 1 );
			ac = new AddonComponent( 167 );
			AddComponent( ac, -4, 0, 1 );
			ac = new AddonComponent( 167 );
			AddComponent( ac, -4, 1, 1 );
			ac = new AddonComponent( 167 );
			AddComponent( ac, -4, 1, 1 );
			ac = new AddonComponent( 190 );
			AddComponent( ac, -4, 2, 1 );
			ac = new AddonComponent( 168 );
			AddComponent( ac, -3, -3, 1 );
			ac = new AddonComponent( 168 );
			AddComponent( ac, -2, -3, 1 );
			ac = new AddonComponent( 168 );
			AddComponent( ac, -1, -3, 1 );
			ac = new AddonComponent( 168 );
			AddComponent( ac, 0, -3, 1 );
			ac = new AddonComponent( 168 );
			AddComponent( ac, 1, -3, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, -3, -2, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, -3, -1, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, -3, 0, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, -3, 1, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, -2, -2, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, -2, -1, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, -2, 0, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, -2, 1, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, -1, -2, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, -1, -1, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, -1, 0, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, -1, 1, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, 0, -2, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, 0, -1, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, 0, 0, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, 0, 1, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, 1, -2, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, 1, -1, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, 1, 0, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, 1, 1, 1 );
			ac = new AddonComponent( 168 );
			AddComponent( ac, -3, 1, 1 );
			ac = new AddonComponent( 2968 );
			AddComponent( ac, -3, 2, 1 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, -3, 2, 1 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, -2, 2, 1 );
			ac = new AddonComponent( 173 );
			AddComponent( ac, -2, 1, 1 );
			ac = new AddonComponent( 1317 );
			AddComponent( ac, -1, 2, 1 );
			ac = new AddonComponent( 171 );
			AddComponent( ac, 0, 1, 1 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 0, 2, 1 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 1, 2, 1 );
			ac = new AddonComponent( 167 );
			AddComponent( ac, 1, -2, 1 );
			ac = new AddonComponent( 185 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 1, -1, 1 );
			ac = new AddonComponent( 167 );
			AddComponent( ac, 1, 0, 1 );
			ac = new AddonComponent( 166 );
			AddComponent( ac, 1, 1, 1 );
			ac = new AddonComponent( 194 );
			AddComponent( ac, -4, -2, 21 );
			ac = new AddonComponent( 194 );
			AddComponent( ac, -4, -1, 21 );
			ac = new AddonComponent( 194 );
			AddComponent( ac, -4, 0, 21 );
			ac = new AddonComponent( 194 );
			AddComponent( ac, -4, 1, 21 );
			ac = new AddonComponent( 193 );
			AddComponent( ac, -3, -3, 21 );
			ac = new AddonComponent( 193 );
			AddComponent( ac, -2, -3, 21 );
			ac = new AddonComponent( 193 );
			AddComponent( ac, -1, -3, 21 );
			ac = new AddonComponent( 193 );
			AddComponent( ac, 0, -3, 21 );
			ac = new AddonComponent( 193 );
			AddComponent( ac, 1, -3, 21 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, -3, -2, 21 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, -3, -1, 21 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, -3, 0, 21 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, -3, 1, 21 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, -2, -2, 21 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, -2, -1, 21 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, -2, 0, 21 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, -2, 1, 21 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, -1, -2, 21 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, -1, -1, 21 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, -1, 0, 21 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, -1, 1, 21 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 0, -2, 21 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 0, -1, 21 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 0, 0, 21 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 0, 1, 21 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 1, -2, 21 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 1, -1, 21 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 1, 0, 21 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 1, 1, 21 );
			ac = new AddonComponent( 193 );
			AddComponent( ac, -3, 1, 21 );
			ac = new AddonComponent( 193 );
			AddComponent( ac, -2, 1, 21 );
			ac = new AddonComponent( 193 );
			AddComponent( ac, -1, 1, 21 );
			ac = new AddonComponent( 193 );
			AddComponent( ac, 0, 1, 21 );
			ac = new AddonComponent( 193 );
			AddComponent( ac, 1, 1, 21 );
			ac = new AddonComponent( 194 );
			AddComponent( ac, 1, -2, 21 );
			ac = new AddonComponent( 194 );
			AddComponent( ac, 1, -1, 21 );
			ac = new AddonComponent( 194 );
			AddComponent( ac, 1, 1, 21 );
			ac = new AddonComponent( 190 );
			AddComponent( ac, -4, 3, 1 );
			ac = new AddonComponent( 190 );
			AddComponent( ac, -4, 4, 1 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, -3, 3, 1 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, -3, 4, 1 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, -2, 3, 1 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, -2, 4, 1 );
			ac = new AddonComponent( 191 );
			AddComponent( ac, -3, 4, 1 );
			ac = new AddonComponent( 191 );
			AddComponent( ac, -2, 4, 1 );
			ac = new AddonComponent( 1317 );
			AddComponent( ac, -1, 3, 1 );
			ac = new AddonComponent( 1317 );
			AddComponent( ac, -1, 4, 1 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 0, 3, 1 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 0, 4, 1 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 1, 3, 1 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 1, 4, 1 );
			ac = new AddonComponent( 191 );
			AddComponent( ac, 0, 4, 1 );
			ac = new AddonComponent( 191 );
			AddComponent( ac, 1, 4, 1 );
			ac = new AddonComponent( 191 );
			AddComponent( ac, 2, -2, 1 );
			ac = new AddonComponent( 191 );
			AddComponent( ac, 3, -2, 1 );
			ac = new AddonComponent( 191 );
			AddComponent( ac, 4, -2, 1 );
			ac = new AddonComponent( 191 );
			AddComponent( ac, 5, -2, 1 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 2, -1, 1 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 2, 0, 1 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 2, 1, 1 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 2, 2, 1 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 3, -1, 1 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 3, 0, 1 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 3, 1, 1 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 3, 2, 1 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 4, -1, 1 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 4, 0, 1 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 4, 1, 1 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 4, 2, 1 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 5, -1, 1 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 5, 0, 1 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 5, 1, 1 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 5, 2, 1 );
			ac = new AddonComponent( 2208 );
			AddComponent( ac, 2, 0, 10 );
			ac = new AddonComponent( 2207 );
			AddComponent( ac, 3, 0, 0 );
			ac = new AddonComponent( 190 );
			AddComponent( ac, 5, -1, 1 );
			ac = new AddonComponent( 190 );
			AddComponent( ac, 5, 0, 1 );
			ac = new AddonComponent( 190 );
			AddComponent( ac, 5, 1, 1 );
			ac = new AddonComponent( 190 );
			AddComponent( ac, 5, 2, 1 );
			ac = new AddonComponent( 191 );
			AddComponent( ac, 2, 4, 1 );
			ac = new AddonComponent( 191 );
			AddComponent( ac, 3, 4, 1 );
			ac = new AddonComponent( 191 );
			AddComponent( ac, 4, 4, 1 );
			ac = new AddonComponent( 191 );
			AddComponent( ac, 5, 4, 1 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 2, 3, 1 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 2, 4, 1 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 3, 3, 1 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 3, 4, 1 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 4, 3, 1 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 4, 4, 1 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 5, 3, 1 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 5, 4, 1 );
			ac = new AddonComponent( 190 );
			AddComponent( ac, 5, 3, 1 );
			ac = new AddonComponent( 190 );
			AddComponent( ac, 5, 4, 1 );

		}

		public casita_madera4Addon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class casita_madera4AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new casita_madera4Addon();
			}
		}

		[Constructable]
		public casita_madera4AddonDeed()
		{
			Name = "casita_madera4";
		}

		public casita_madera4AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}