/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace troncos
{
	public class casitaAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new casitaAddonDeed();
			}
		}

		[ Constructable ]
		public casitaAddon()
		{
			AddonComponent ac = null;
			ac = new AddonComponent( 147 );
			AddComponent( ac, -4, -4, 0 );
			ac = new AddonComponent( 149 );
			AddComponent( ac, -3, -4, 0 );
			ac = new AddonComponent( 146 );
			AddComponent( ac, -2, -4, 0 );
			ac = new AddonComponent( 146 );
			AddComponent( ac, -1, -4, 0 );
			ac = new AddonComponent( 146 );
			AddComponent( ac, 0, -4, 0 );
			ac = new AddonComponent( 148 );
			AddComponent( ac, -4, -3, 0 );
			ac = new AddonComponent( 145 );
			AddComponent( ac, -4, -2, 0 );
			ac = new AddonComponent( 153 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, -4, -1, 0 );
			ac = new AddonComponent( 145 );
			AddComponent( ac, -4, 0, 0 );
			ac = new AddonComponent( 145 );
			AddComponent( ac, -4, 1, 0 );
			ac = new AddonComponent( 153 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, -4, 2, 0 );
			ac = new AddonComponent( 145 );
			AddComponent( ac, -4, 3, 0 );
			ac = new AddonComponent( 150 );
			AddComponent( ac, -4, 4, 0 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, -3, -3, 1 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, -3, -2, 1 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, -3, -1, 1 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, -3, 0, 1 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, -3, 1, 1 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, -3, 2, 1 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, -3, 3, 1 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, -3, 4, 1 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, -2, -3, 1 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, -2, -2, 1 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, -2, -1, 1 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, -2, 0, 1 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, -2, 1, 1 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, -2, 2, 1 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, -2, 3, 1 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, -2, 4, 1 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, -1, -3, 1 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, -1, -2, 1 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, -1, -1, 1 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, -1, 0, 1 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, -1, 1, 1 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, -1, 2, 1 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, -1, 3, 1 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, -1, 4, 1 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 0, -3, 1 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 0, -2, 1 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 0, -1, 1 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 0, 0, 1 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 0, 1, 1 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 0, 2, 1 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 0, 3, 1 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 0, 4, 1 );
			ac = new AddonComponent( 149 );
			AddComponent( ac, -3, 4, 0 );
			ac = new AddonComponent( 146 );
			AddComponent( ac, -2, 4, 0 );
			ac = new AddonComponent( 146 );
			AddComponent( ac, -1, 4, 0 );
			ac = new AddonComponent( 1449 );
			AddComponent( ac, -3, -3, 20 );
			ac = new AddonComponent( 1449 );
			AddComponent( ac, -2, -3, 20 );
			ac = new AddonComponent( 1449 );
			AddComponent( ac, -1, -3, 20 );
			ac = new AddonComponent( 1449 );
			AddComponent( ac, 0, -3, 20 );
			ac = new AddonComponent( 1449 );
			AddComponent( ac, -3, -2, 23 );
			ac = new AddonComponent( 1449 );
			AddComponent( ac, -2, -2, 23 );
			ac = new AddonComponent( 1449 );
			AddComponent( ac, -1, -2, 23 );
			ac = new AddonComponent( 1449 );
			AddComponent( ac, 0, -2, 23 );
			ac = new AddonComponent( 1449 );
			AddComponent( ac, -3, -1, 26 );
			ac = new AddonComponent( 1449 );
			AddComponent( ac, -2, -1, 26 );
			ac = new AddonComponent( 1449 );
			AddComponent( ac, -1, -1, 26 );
			ac = new AddonComponent( 1449 );
			AddComponent( ac, 0, -1, 26 );
			ac = new AddonComponent( 1449 );
			AddComponent( ac, -3, 0, 29 );
			ac = new AddonComponent( 1449 );
			AddComponent( ac, -2, 0, 29 );
			ac = new AddonComponent( 1449 );
			AddComponent( ac, -1, 0, 29 );
			ac = new AddonComponent( 1449 );
			AddComponent( ac, 0, 0, 29 );
			ac = new AddonComponent( 1448 );
			AddComponent( ac, -3, 1, 32 );
			ac = new AddonComponent( 1448 );
			AddComponent( ac, -2, 1, 32 );
			ac = new AddonComponent( 1448 );
			AddComponent( ac, -1, 1, 32 );
			ac = new AddonComponent( 1448 );
			AddComponent( ac, 0, 1, 32 );
			ac = new AddonComponent( 1447 );
			AddComponent( ac, -3, 2, 29 );
			ac = new AddonComponent( 1447 );
			AddComponent( ac, -2, 2, 29 );
			ac = new AddonComponent( 1447 );
			AddComponent( ac, -1, 2, 29 );
			ac = new AddonComponent( 1447 );
			AddComponent( ac, 0, 2, 29 );
			ac = new AddonComponent( 1447 );
			AddComponent( ac, -3, 3, 26 );
			ac = new AddonComponent( 1447 );
			AddComponent( ac, -2, 3, 26 );
			ac = new AddonComponent( 1447 );
			AddComponent( ac, -1, 3, 26 );
			ac = new AddonComponent( 1447 );
			AddComponent( ac, 0, 3, 26 );
			ac = new AddonComponent( 1447 );
			AddComponent( ac, -3, 4, 23 );
			ac = new AddonComponent( 1447 );
			AddComponent( ac, -2, 4, 23 );
			ac = new AddonComponent( 1447 );
			AddComponent( ac, -1, 4, 23 );
			ac = new AddonComponent( 1447 );
			AddComponent( ac, 0, 4, 23 );
			ac = new AddonComponent( 1447 );
			AddComponent( ac, -3, 5, 20 );
			ac = new AddonComponent( 1447 );
			AddComponent( ac, -2, 5, 20 );
			ac = new AddonComponent( 1447 );
			AddComponent( ac, -1, 5, 20 );
			ac = new AddonComponent( 1447 );
			AddComponent( ac, 0, 5, 20 );
			ac = new AddonComponent( 146 );
			AddComponent( ac, 1, -4, 0 );
			ac = new AddonComponent( 146 );
			AddComponent( ac, 2, -4, 0 );
			ac = new AddonComponent( 146 );
			AddComponent( ac, 3, -4, 0 );
			ac = new AddonComponent( 151 );
			AddComponent( ac, 4, -4, 0 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 1, -3, 1 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 1, -2, 1 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 1, -1, 1 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 1, 0, 1 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 1, 1, 1 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 1, 2, 1 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 1, 3, 1 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 1, 4, 1 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 2, -3, 1 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 2, -2, 1 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 2, -1, 1 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 2, 0, 1 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 2, 1, 1 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 2, 2, 1 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 2, 3, 1 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 2, 4, 1 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 3, -3, 1 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 3, -2, 1 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 3, -1, 1 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 3, 0, 1 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 3, 1, 1 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 3, 2, 1 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 3, 3, 1 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 3, 4, 1 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 4, -3, 1 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 4, -2, 1 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 4, -1, 1 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 4, 0, 1 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 4, 1, 1 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 4, 2, 1 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 4, 3, 1 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 4, 4, 1 );
			ac = new AddonComponent( 146 );
			AddComponent( ac, 1, 4, 0 );
			ac = new AddonComponent( 146 );
			AddComponent( ac, 2, 4, 0 );
			ac = new AddonComponent( 146 );
			AddComponent( ac, 3, 4, 0 );
			ac = new AddonComponent( 148 );
			AddComponent( ac, 4, -3, 0 );
			ac = new AddonComponent( 145 );
			AddComponent( ac, 4, -2, 0 );
			ac = new AddonComponent( 153 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 4, -1, 0 );
			ac = new AddonComponent( 145 );
			AddComponent( ac, 4, 0, 0 );
			ac = new AddonComponent( 145 );
			AddComponent( ac, 4, 1, 0 );
			ac = new AddonComponent( 153 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 4, 2, 0 );
			ac = new AddonComponent( 145 );
			AddComponent( ac, 4, 3, 0 );
			ac = new AddonComponent( 144 );
			AddComponent( ac, 4, 4, 0 );
			ac = new AddonComponent( 1449 );
			AddComponent( ac, 1, -3, 20 );
			ac = new AddonComponent( 1449 );
			AddComponent( ac, 2, -3, 20 );
			ac = new AddonComponent( 1449 );
			AddComponent( ac, 3, -3, 20 );
			ac = new AddonComponent( 1449 );
			AddComponent( ac, 4, -3, 20 );
			ac = new AddonComponent( 1449 );
			AddComponent( ac, 5, -3, 20 );
			ac = new AddonComponent( 1449 );
			AddComponent( ac, 1, -2, 23 );
			ac = new AddonComponent( 1449 );
			AddComponent( ac, 2, -2, 23 );
			ac = new AddonComponent( 1449 );
			AddComponent( ac, 3, -2, 23 );
			ac = new AddonComponent( 1449 );
			AddComponent( ac, 4, -2, 23 );
			ac = new AddonComponent( 1449 );
			AddComponent( ac, 5, -2, 23 );
			ac = new AddonComponent( 1449 );
			AddComponent( ac, 1, -1, 26 );
			ac = new AddonComponent( 1449 );
			AddComponent( ac, 2, -1, 26 );
			ac = new AddonComponent( 1449 );
			AddComponent( ac, 3, -1, 26 );
			ac = new AddonComponent( 1449 );
			AddComponent( ac, 4, -1, 26 );
			ac = new AddonComponent( 1449 );
			AddComponent( ac, 5, -1, 26 );
			ac = new AddonComponent( 1449 );
			AddComponent( ac, 1, 0, 29 );
			ac = new AddonComponent( 1449 );
			AddComponent( ac, 2, 0, 29 );
			ac = new AddonComponent( 1449 );
			AddComponent( ac, 3, 0, 29 );
			ac = new AddonComponent( 1449 );
			AddComponent( ac, 4, 0, 29 );
			ac = new AddonComponent( 1449 );
			AddComponent( ac, 5, 0, 29 );
			ac = new AddonComponent( 1448 );
			AddComponent( ac, 1, 1, 32 );
			ac = new AddonComponent( 1448 );
			AddComponent( ac, 2, 1, 32 );
			ac = new AddonComponent( 1448 );
			AddComponent( ac, 3, 1, 32 );
			ac = new AddonComponent( 1448 );
			AddComponent( ac, 4, 1, 32 );
			ac = new AddonComponent( 1448 );
			AddComponent( ac, 5, 1, 32 );
			ac = new AddonComponent( 1447 );
			AddComponent( ac, 1, 2, 29 );
			ac = new AddonComponent( 1447 );
			AddComponent( ac, 2, 2, 29 );
			ac = new AddonComponent( 1447 );
			AddComponent( ac, 3, 2, 29 );
			ac = new AddonComponent( 1447 );
			AddComponent( ac, 4, 2, 29 );
			ac = new AddonComponent( 1447 );
			AddComponent( ac, 5, 2, 29 );
			ac = new AddonComponent( 1447 );
			AddComponent( ac, 1, 3, 26 );
			ac = new AddonComponent( 1447 );
			AddComponent( ac, 2, 3, 26 );
			ac = new AddonComponent( 1447 );
			AddComponent( ac, 3, 3, 26 );
			ac = new AddonComponent( 1447 );
			AddComponent( ac, 4, 3, 26 );
			ac = new AddonComponent( 1447 );
			AddComponent( ac, 5, 3, 26 );
			ac = new AddonComponent( 1447 );
			AddComponent( ac, 1, 4, 23 );
			ac = new AddonComponent( 1447 );
			AddComponent( ac, 2, 4, 23 );
			ac = new AddonComponent( 1447 );
			AddComponent( ac, 3, 4, 23 );
			ac = new AddonComponent( 1447 );
			AddComponent( ac, 4, 4, 23 );
			ac = new AddonComponent( 1447 );
			AddComponent( ac, 5, 4, 23 );
			ac = new AddonComponent( 1447 );
			AddComponent( ac, 1, 5, 20 );
			ac = new AddonComponent( 1447 );
			AddComponent( ac, 2, 5, 20 );
			ac = new AddonComponent( 1447 );
			AddComponent( ac, 3, 5, 20 );
			ac = new AddonComponent( 1447 );
			AddComponent( ac, 4, 5, 20 );
			ac = new AddonComponent( 1447 );
			AddComponent( ac, 5, 5, 20 );
			ac = new AddonComponent( 165 );
			AddComponent( ac, 4, -2, 20 );
			ac = new AddonComponent( 165 );
			AddComponent( ac, 4, -1, 20 );
			ac = new AddonComponent( 165 );
			AddComponent( ac, 4, 0, 20 );
			ac = new AddonComponent( 165 );
			AddComponent( ac, 4, 1, 20 );
			ac = new AddonComponent( 165 );
			AddComponent( ac, 4, 2, 20 );
			ac = new AddonComponent( 165 );
			AddComponent( ac, 4, 3, 20 );
			ac = new AddonComponent( 165 );
			AddComponent( ac, 4, -2, 22 );
			ac = new AddonComponent( 165 );
			AddComponent( ac, 4, -1, 23 );
			ac = new AddonComponent( 165 );
			AddComponent( ac, 4, 0, 23 );
			ac = new AddonComponent( 165 );
			AddComponent( ac, 4, 1, 23 );
			ac = new AddonComponent( 165 );
			AddComponent( ac, 4, 2, 23 );
			ac = new AddonComponent( 165 );
			AddComponent( ac, 4, -1, 25 );
			ac = new AddonComponent( 165 );
			AddComponent( ac, 4, 0, 26 );
			ac = new AddonComponent( 165 );
			AddComponent( ac, 4, 1, 26 );
			ac = new AddonComponent( 165 );
			AddComponent( ac, 4, 0, 28 );

		}

		public casitaAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class casitaAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new casitaAddon();
			}
		}

		[Constructable]
		public casitaAddonDeed()
		{
			Name = "casita";
		}

		public casitaAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}