/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class casitamaderaAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new casitamaderaAddonDeed();
			}
		}

		[ Constructable ]
		public casitamaderaAddon()
		{
			AddonComponent ac = null;
			ac = new AddonComponent( 1189 );
			AddComponent( ac, -2, -2, 0 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, -1, -2, 0 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, 0, -2, 0 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, 1, -2, 0 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, 2, -2, 0 );
			ac = new AddonComponent( 167 );
			AddComponent( ac, -2, -1, 0 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, -2, 0, 0 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, -2, 1, 0 );
			ac = new AddonComponent( 185 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, -2, 0, 0 );
			ac = new AddonComponent( 167 );
			AddComponent( ac, -2, 1, 0 );
			ac = new AddonComponent( 167 );
			AddComponent( ac, -2, 2, 0 );
			ac = new AddonComponent( 167 );
			AddComponent( ac, -2, 2, 0 );
			ac = new AddonComponent( 168 );
			AddComponent( ac, -1, -2, 0 );
			ac = new AddonComponent( 168 );
			AddComponent( ac, 0, -2, 0 );
			ac = new AddonComponent( 168 );
			AddComponent( ac, 1, -2, 0 );
			ac = new AddonComponent( 168 );
			AddComponent( ac, 2, -2, 0 );
			ac = new AddonComponent( 168 );
			AddComponent( ac, 3, -2, 0 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, -1, 2, 0 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, 0, 2, 0 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, 1, 2, 0 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, 2, 2, 0 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, 3, -1, 0 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, 3, 0, 0 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, 3, 1, 0 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, 3, 2, 0 );
			ac = new AddonComponent( 168 );
			AddComponent( ac, -1, 2, 0 );
			ac = new AddonComponent( 2968 );
			AddComponent( ac, -1, 3, 0 );
			ac = new AddonComponent( 3026 );
			AddComponent( ac, -1, 3, 0 );
			ac = new AddonComponent( 173 );
			AddComponent( ac, 0, 2, 0 );
			ac = new AddonComponent( 171 );
			AddComponent( ac, 2, 2, 0 );
			ac = new AddonComponent( 167 );
			AddComponent( ac, 3, -1, 0 );
			ac = new AddonComponent( 185 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 3, 0, 0 );
			ac = new AddonComponent( 167 );
			AddComponent( ac, 3, 1, 0 );
			ac = new AddonComponent( 166 );
			AddComponent( ac, 3, 2, 0 );
			ac = new AddonComponent( 194 );
			AddComponent( ac, -2, -1, 20 );
			ac = new AddonComponent( 194 );
			AddComponent( ac, -2, 0, 20 );
			ac = new AddonComponent( 194 );
			AddComponent( ac, -2, 1, 20 );
			ac = new AddonComponent( 194 );
			AddComponent( ac, -2, 2, 20 );
			ac = new AddonComponent( 193 );
			AddComponent( ac, -1, -2, 20 );
			ac = new AddonComponent( 193 );
			AddComponent( ac, 0, -2, 20 );
			ac = new AddonComponent( 193 );
			AddComponent( ac, 1, -2, 20 );
			ac = new AddonComponent( 193 );
			AddComponent( ac, 2, -2, 20 );
			ac = new AddonComponent( 193 );
			AddComponent( ac, 3, -2, 20 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, -1, -1, 20 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, -1, 0, 20 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, -1, 1, 20 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, -1, 2, 20 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 0, -1, 20 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 0, 0, 20 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 0, 1, 20 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 0, 2, 20 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 1, -1, 20 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 1, 0, 20 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 1, 1, 20 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 1, 2, 20 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 2, -1, 20 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 2, 0, 20 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 2, 1, 20 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 2, 2, 20 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 3, -1, 20 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 3, 0, 20 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 3, 1, 20 );
			ac = new AddonComponent( 1223 );
			AddComponent( ac, 3, 2, 20 );
			ac = new AddonComponent( 193 );
			AddComponent( ac, -1, 2, 20 );
			ac = new AddonComponent( 193 );
			AddComponent( ac, 0, 2, 20 );
			ac = new AddonComponent( 193 );
			AddComponent( ac, 1, 2, 20 );
			ac = new AddonComponent( 193 );
			AddComponent( ac, 2, 2, 20 );
			ac = new AddonComponent( 193 );
			AddComponent( ac, 3, 2, 20 );
			ac = new AddonComponent( 194 );
			AddComponent( ac, 3, -1, 20 );
			ac = new AddonComponent( 194 );
			AddComponent( ac, 3, 0, 20 );
			ac = new AddonComponent( 194 );
			AddComponent( ac, 3, 1, 20 );
			ac = new AddonComponent( 194 );
			AddComponent( ac, 3, 2, 20 );

		}

		public casitamaderaAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class casitamaderaAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new casitamaderaAddon();
			}
		}

		[Constructable]
		public casitamaderaAddonDeed()
		{
			Name = "casitamadera";
		}

		public casitamaderaAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}