/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class casita_marmolAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new casita_marmolAddonDeed();
			}
		}

		[ Constructable ]
		public casita_marmolAddon()
		{
			AddonComponent ac = null;
			ac = new AddonComponent( 4643 );
			AddComponent( ac, -2, -2, 0 );
			ac = new AddonComponent( 4643 );
			AddComponent( ac, -2, -1, 0 );
			ac = new AddonComponent( 4643 );
			AddComponent( ac, -2, 0, 0 );
			ac = new AddonComponent( 4643 );
			AddComponent( ac, -2, 1, 0 );
			ac = new AddonComponent( 1173 );
			AddComponent( ac, -2, -2, 6 );
			ac = new AddonComponent( 1173 );
			AddComponent( ac, -2, -1, 6 );
			ac = new AddonComponent( 1173 );
			AddComponent( ac, -2, 0, 6 );
			ac = new AddonComponent( 1173 );
			AddComponent( ac, -2, 1, 6 );
			ac = new AddonComponent( 659 );
			AddComponent( ac, -2, -1, 6 );
			ac = new AddonComponent( 659 );
			AddComponent( ac, -2, 0, 6 );
			ac = new AddonComponent( 659 );
			AddComponent( ac, -2, 1, 6 );
			ac = new AddonComponent( 659 );
			AddComponent( ac, -2, 2, 6 );
			ac = new AddonComponent( 4643 );
			AddComponent( ac, -1, -2, 0 );
			ac = new AddonComponent( 4643 );
			AddComponent( ac, 0, -2, 0 );
			ac = new AddonComponent( 4643 );
			AddComponent( ac, 1, -2, 0 );
			ac = new AddonComponent( 4643 );
			AddComponent( ac, 2, -2, 0 );
			ac = new AddonComponent( 1173 );
			AddComponent( ac, -1, -2, 6 );
			ac = new AddonComponent( 1173 );
			AddComponent( ac, -1, -1, 6 );
			ac = new AddonComponent( 1173 );
			AddComponent( ac, -1, 0, 6 );
			ac = new AddonComponent( 1173 );
			AddComponent( ac, -1, 1, 6 );
			ac = new AddonComponent( 1173 );
			AddComponent( ac, -1, 2, 6 );
			ac = new AddonComponent( 1173 );
			AddComponent( ac, 0, -2, 6 );
			ac = new AddonComponent( 1173 );
			AddComponent( ac, 0, -1, 6 );
			ac = new AddonComponent( 1173 );
			AddComponent( ac, 0, 0, 6 );
			ac = new AddonComponent( 1173 );
			AddComponent( ac, 0, 1, 6 );
			ac = new AddonComponent( 1173 );
			AddComponent( ac, 0, 2, 6 );
			ac = new AddonComponent( 1173 );
			AddComponent( ac, 1, -2, 6 );
			ac = new AddonComponent( 1173 );
			AddComponent( ac, 1, -1, 6 );
			ac = new AddonComponent( 1173 );
			AddComponent( ac, 1, 0, 6 );
			ac = new AddonComponent( 1173 );
			AddComponent( ac, 1, 1, 6 );
			ac = new AddonComponent( 1173 );
			AddComponent( ac, 1, 2, 6 );
			ac = new AddonComponent( 1173 );
			AddComponent( ac, 2, -2, 6 );
			ac = new AddonComponent( 1173 );
			AddComponent( ac, 2, -1, 6 );
			ac = new AddonComponent( 1173 );
			AddComponent( ac, 2, 0, 6 );
			ac = new AddonComponent( 1173 );
			AddComponent( ac, 2, 1, 6 );
			ac = new AddonComponent( 1173 );
			AddComponent( ac, 2, 2, 6 );
			ac = new AddonComponent( 658 );
			AddComponent( ac, -1, -2, 6 );
			ac = new AddonComponent( 658 );
			AddComponent( ac, 0, -2, 6 );
			ac = new AddonComponent( 658 );
			AddComponent( ac, 1, -2, 6 );
			ac = new AddonComponent( 658 );
			AddComponent( ac, 2, -2, 6 );
			ac = new AddonComponent( 658 );
			AddComponent( ac, 3, -2, 6 );
			ac = new AddonComponent( 4643 );
			AddComponent( ac, -1, 2, 0 );
			ac = new AddonComponent( 4643 );
			AddComponent( ac, 0, 2, 0 );
			ac = new AddonComponent( 658 );
			AddComponent( ac, -1, 2, 6 );
			ac = new AddonComponent( 658 );
			AddComponent( ac, 0, 2, 6 );
			ac = new AddonComponent( 1812 );
			AddComponent( ac, 0, 3, 1 );
			ac = new AddonComponent( 1802 );
			AddComponent( ac, 1, 3, 1 );
			ac = new AddonComponent( 4643 );
			AddComponent( ac, 2, 2, 0 );
			ac = new AddonComponent( 4643 );
			AddComponent( ac, 3, 2, 0 );
			ac = new AddonComponent( 658 );
			AddComponent( ac, 2, 2, 6 );
			ac = new AddonComponent( 658 );
			AddComponent( ac, 3, 2, 6 );
			ac = new AddonComponent( 1811 );
			AddComponent( ac, 2, 3, 1 );
			ac = new AddonComponent( 4643 );
			AddComponent( ac, 3, -1, 0 );
			ac = new AddonComponent( 4643 );
			AddComponent( ac, 3, 0, 0 );
			ac = new AddonComponent( 4643 );
			AddComponent( ac, 3, 1, 0 );
			ac = new AddonComponent( 1173 );
			AddComponent( ac, 3, -1, 6 );
			ac = new AddonComponent( 1173 );
			AddComponent( ac, 3, 0, 6 );
			ac = new AddonComponent( 1173 );
			AddComponent( ac, 3, 1, 6 );
			ac = new AddonComponent( 1173 );
			AddComponent( ac, 3, 2, 6 );
			ac = new AddonComponent( 659 );
			AddComponent( ac, 3, -1, 6 );
			ac = new AddonComponent( 659 );
			AddComponent( ac, 3, 0, 6 );
			ac = new AddonComponent( 659 );
			AddComponent( ac, 3, 1, 6 );
			ac = new AddonComponent( 659 );
			AddComponent( ac, 3, 2, 6 );
			ac = new AddonComponent( 695 );
			AddComponent( ac, -2, -1, 26 );
			ac = new AddonComponent( 695 );
			AddComponent( ac, -2, 0, 26 );
			ac = new AddonComponent( 695 );
			AddComponent( ac, -2, 1, 26 );
			ac = new AddonComponent( 695 );
			AddComponent( ac, -2, 2, 26 );
			ac = new AddonComponent( 694 );
			AddComponent( ac, -1, -2, 26 );
			ac = new AddonComponent( 694 );
			AddComponent( ac, 0, -2, 26 );
			ac = new AddonComponent( 694 );
			AddComponent( ac, 1, -2, 26 );
			ac = new AddonComponent( 694 );
			AddComponent( ac, 2, -2, 26 );
			ac = new AddonComponent( 694 );
			AddComponent( ac, 3, -2, 26 );
			ac = new AddonComponent( 1293 );
			AddComponent( ac, -1, -1, 26 );
			ac = new AddonComponent( 1293 );
			AddComponent( ac, -1, 0, 26 );
			ac = new AddonComponent( 1293 );
			AddComponent( ac, -1, 1, 26 );
			ac = new AddonComponent( 1293 );
			AddComponent( ac, -1, 2, 26 );
			ac = new AddonComponent( 1293 );
			AddComponent( ac, -1, -1, 26 );
			ac = new AddonComponent( 1293 );
			AddComponent( ac, 0, -1, 26 );
			ac = new AddonComponent( 1293 );
			AddComponent( ac, 1, -1, 26 );
			ac = new AddonComponent( 1293 );
			AddComponent( ac, 2, -1, 26 );
			ac = new AddonComponent( 1293 );
			AddComponent( ac, 3, -1, 26 );
			ac = new AddonComponent( 694 );
			AddComponent( ac, -1, 2, 26 );
			ac = new AddonComponent( 694 );
			AddComponent( ac, 0, 2, 26 );
			ac = new AddonComponent( 694 );
			AddComponent( ac, 1, 2, 26 );
			ac = new AddonComponent( 694 );
			AddComponent( ac, 2, 2, 26 );
			ac = new AddonComponent( 694 );
			AddComponent( ac, 3, 2, 26 );
			ac = new AddonComponent( 1293 );
			AddComponent( ac, 0, 0, 26 );
			ac = new AddonComponent( 1293 );
			AddComponent( ac, 0, 1, 26 );
			ac = new AddonComponent( 1293 );
			AddComponent( ac, 0, 2, 26 );
			ac = new AddonComponent( 1293 );
			AddComponent( ac, 1, 0, 26 );
			ac = new AddonComponent( 1293 );
			AddComponent( ac, 1, 1, 26 );
			ac = new AddonComponent( 1293 );
			AddComponent( ac, 1, 2, 26 );
			ac = new AddonComponent( 1293 );
			AddComponent( ac, 2, 0, 26 );
			ac = new AddonComponent( 1293 );
			AddComponent( ac, 2, 1, 26 );
			ac = new AddonComponent( 1293 );
			AddComponent( ac, 2, 2, 26 );
			ac = new AddonComponent( 1293 );
			AddComponent( ac, 2, 2, 26 );
			ac = new AddonComponent( 1293 );
			AddComponent( ac, 3, 2, 26 );
			ac = new AddonComponent( 695 );
			AddComponent( ac, 3, -1, 26 );
			ac = new AddonComponent( 695 );
			AddComponent( ac, 3, 0, 26 );
			ac = new AddonComponent( 695 );
			AddComponent( ac, 3, 1, 26 );
			ac = new AddonComponent( 695 );
			AddComponent( ac, 3, 2, 26 );
			ac = new AddonComponent( 1293 );
			AddComponent( ac, 3, 0, 26 );
			ac = new AddonComponent( 1293 );
			AddComponent( ac, 3, 1, 26 );

		}

		public casita_marmolAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class casita_marmolAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new casita_marmolAddon();
			}
		}

		[Constructable]
		public casita_marmolAddonDeed()
		{
			Name = "casita_marmol";
		}

		public casita_marmolAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}