
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class EnchantedPicinicSouthAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {41175, 0, 1, 4}, {41178, 1, 1, 5}, {41177, 1, 0, 5}// 1	2	3	
			, {41179, 0, 0, 1}, {41173, 1, 0, 0}, {2519, 1, 0, 1}// 4	5	6	
			, {41172, 1, 1, 0}, {41171, 0, 0, 0}, {8092, -1, 0, 1}// 7	8	9	
			, {41169, -1, 0, 0}, {41170, 0, 1, 0}, {2519, 0, 1, 1}// 10	11	12	
			, {2519, 1, 1, 1}, {41168, -1, 1, 0}// 13	14	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new EnchantedPicinicSouthAddonDeed();
			}
		}

		[ Constructable ]
		public EnchantedPicinicSouthAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public EnchantedPicinicSouthAddon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class EnchantedPicinicSouthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new EnchantedPicinicSouthAddon();
			}
		}

		[Constructable]
		public EnchantedPicinicSouthAddonDeed()
		{
			Name = "EnchantedPicinicSouth";
		}

		public EnchantedPicinicSouthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}