
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class FormalDiningTableE2WAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {40318, 3, 1, 0}, {40317, 3, 0, 0}, {40316, 2, 1, 0}// 1	2	3	
			, {40315, 2, 0, 0}, {40314, 1, 1, 0}, {40313, 1, 0, 0}// 4	5	6	
			, {40312, 0, 1, 0}, {40311, 0, 0, 0}, {40310, -1, 1, 0}// 7	8	9	
			, {40309, -1, 0, 0}, {40308, -2, 1, 0}, {40307, -2, 0, 0}// 10	11	12	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new FormalDiningTableE2WAddonDeed();
			}
		}

		[ Constructable ]
		public FormalDiningTableE2WAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public FormalDiningTableE2WAddon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class FormalDiningTableE2WAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new FormalDiningTableE2WAddon();
			}
		}

		[Constructable]
		public FormalDiningTableE2WAddonDeed()
		{
			Name = "Formal Dining Table E2W";
		}

		public FormalDiningTableE2WAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}