/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class monglowAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new monglowAddonDeed();
			}
		}

		[ Constructable ]
		public monglowAddon()
		{
			AddonComponent ac = null;
			ac = new AddonComponent( 298 );
			AddComponent( ac, -4, -4, 0 );
			ac = new AddonComponent( 311 );
			AddComponent( ac, -4, -3, 0 );
			ac = new AddonComponent( 311 );
			AddComponent( ac, -4, -2, 0 );
			ac = new AddonComponent( 315 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, -4, -1, 0 );
			ac = new AddonComponent( 311 );
			AddComponent( ac, -4, 0, 0 );
			ac = new AddonComponent( 310 );
			AddComponent( ac, -3, -4, 0 );
			ac = new AddonComponent( 310 );
			AddComponent( ac, -2, -4, 0 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, -3, -3, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, -3, -2, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, -3, -1, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, -3, 0, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, -2, -3, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, -2, -2, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, -2, -1, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, -2, 0, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, -1, -3, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, -1, -2, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, -1, -1, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, -1, 0, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, 0, -3, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, 0, -2, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, 0, -1, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, 0, 0, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, 1, -3, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, 1, -2, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, 1, -1, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, 1, 0, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, 2, -3, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, 2, -2, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, 2, -1, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, 2, 0, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, 3, -3, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, 3, -2, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, 3, -1, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, 3, 0, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, 4, -3, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, 4, -2, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, 4, -1, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, 4, 0, 1 );
			ac = new AddonComponent( 314 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, -1, -4, 0 );
			ac = new AddonComponent( 310 );
			AddComponent( ac, 0, -4, 0 );
			ac = new AddonComponent( 310 );
			AddComponent( ac, 1, -4, 0 );
			ac = new AddonComponent( 314 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 2, -4, 0 );
			ac = new AddonComponent( 310 );
			AddComponent( ac, 3, -4, 0 );
			ac = new AddonComponent( 310 );
			AddComponent( ac, 4, -4, 0 );
			ac = new AddonComponent( 311 );
			AddComponent( ac, 4, -3, 0 );
			ac = new AddonComponent( 311 );
			AddComponent( ac, 4, -2, 0 );
			ac = new AddonComponent( 315 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 4, -1, 0 );
			ac = new AddonComponent( 311 );
			AddComponent( ac, 4, 0, 0 );
			ac = new AddonComponent( 1476 );
			AddComponent( ac, -3, -3, 20 );
			ac = new AddonComponent( 1476 );
			AddComponent( ac, -3, -2, 20 );
			ac = new AddonComponent( 1476 );
			AddComponent( ac, -3, -1, 20 );
			ac = new AddonComponent( 1476 );
			AddComponent( ac, -3, 0, 20 );
			ac = new AddonComponent( 1476 );
			AddComponent( ac, -2, -3, 23 );
			ac = new AddonComponent( 1476 );
			AddComponent( ac, -2, -2, 23 );
			ac = new AddonComponent( 1476 );
			AddComponent( ac, -2, -1, 23 );
			ac = new AddonComponent( 1476 );
			AddComponent( ac, -2, 0, 23 );
			ac = new AddonComponent( 1476 );
			AddComponent( ac, -1, -3, 26 );
			ac = new AddonComponent( 1476 );
			AddComponent( ac, -1, -2, 26 );
			ac = new AddonComponent( 1476 );
			AddComponent( ac, -1, -1, 26 );
			ac = new AddonComponent( 1476 );
			AddComponent( ac, -1, 0, 26 );
			ac = new AddonComponent( 1476 );
			AddComponent( ac, 0, -3, 29 );
			ac = new AddonComponent( 1476 );
			AddComponent( ac, 0, -2, 29 );
			ac = new AddonComponent( 1476 );
			AddComponent( ac, 0, -1, 29 );
			ac = new AddonComponent( 1476 );
			AddComponent( ac, 0, 0, 29 );
			ac = new AddonComponent( 1474 );
			AddComponent( ac, 1, -3, 32 );
			ac = new AddonComponent( 1474 );
			AddComponent( ac, 1, -2, 32 );
			ac = new AddonComponent( 1474 );
			AddComponent( ac, 1, -1, 32 );
			ac = new AddonComponent( 1474 );
			AddComponent( ac, 1, 0, 32 );
			ac = new AddonComponent( 1475 );
			AddComponent( ac, 2, -3, 29 );
			ac = new AddonComponent( 1475 );
			AddComponent( ac, 2, -2, 29 );
			ac = new AddonComponent( 1475 );
			AddComponent( ac, 2, -1, 29 );
			ac = new AddonComponent( 1475 );
			AddComponent( ac, 2, 0, 29 );
			ac = new AddonComponent( 1475 );
			AddComponent( ac, 3, -3, 26 );
			ac = new AddonComponent( 1475 );
			AddComponent( ac, 3, -2, 26 );
			ac = new AddonComponent( 1475 );
			AddComponent( ac, 3, -1, 26 );
			ac = new AddonComponent( 1475 );
			AddComponent( ac, 3, 0, 26 );
			ac = new AddonComponent( 1475 );
			AddComponent( ac, 4, -3, 23 );
			ac = new AddonComponent( 1475 );
			AddComponent( ac, 4, -2, 23 );
			ac = new AddonComponent( 1475 );
			AddComponent( ac, 4, -1, 23 );
			ac = new AddonComponent( 1475 );
			AddComponent( ac, 4, 0, 23 );
			ac = new AddonComponent( 1475 );
			AddComponent( ac, 5, -3, 20 );
			ac = new AddonComponent( 1475 );
			AddComponent( ac, 5, -2, 20 );
			ac = new AddonComponent( 1475 );
			AddComponent( ac, 5, -1, 20 );
			ac = new AddonComponent( 1475 );
			AddComponent( ac, 5, 0, 20 );
			ac = new AddonComponent( 311 );
			AddComponent( ac, -4, 1, 0 );
			ac = new AddonComponent( 315 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, -4, 2, 0 );
			ac = new AddonComponent( 311 );
			AddComponent( ac, -4, 3, 0 );
			ac = new AddonComponent( 311 );
			AddComponent( ac, -4, 4, 0 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, -3, 1, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, -3, 2, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, -3, 3, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, -3, 4, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, -2, 1, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, -2, 2, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, -2, 3, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, -2, 4, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, -1, 1, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, -1, 2, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, -1, 3, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, -1, 4, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, 0, 1, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, 0, 2, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, 0, 3, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, 0, 4, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, 1, 1, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, 1, 2, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, 1, 3, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, 1, 4, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, 2, 1, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, 2, 2, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, 2, 3, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, 2, 4, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, 3, 1, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, 3, 2, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, 3, 3, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, 3, 4, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, 4, 1, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, 4, 2, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, 4, 3, 1 );
			ac = new AddonComponent( 1189 );
			AddComponent( ac, 4, 4, 1 );
			ac = new AddonComponent( 310 );
			AddComponent( ac, -3, 4, 0 );
			ac = new AddonComponent( 307 );
			AddComponent( ac, -2, 4, 0 );
			ac = new AddonComponent( 312 );
			AddComponent( ac, 0, 4, 0 );
			ac = new AddonComponent( 310 );
			AddComponent( ac, 1, 4, 0 );
			ac = new AddonComponent( 330 );
			AddComponent( ac, 2, 3, 0 );
			ac = new AddonComponent( 314 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 2, 4, 0 );
			ac = new AddonComponent( 310 );
			AddComponent( ac, 3, 4, 0 );
			ac = new AddonComponent( 311 );
			AddComponent( ac, 4, 1, 0 );
			ac = new AddonComponent( 315 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 4, 2, 0 );
			ac = new AddonComponent( 311 );
			AddComponent( ac, 4, 3, 0 );
			ac = new AddonComponent( 309 );
			AddComponent( ac, 4, 4, 0 );
			ac = new AddonComponent( 1476 );
			AddComponent( ac, -3, 1, 20 );
			ac = new AddonComponent( 1476 );
			AddComponent( ac, -3, 2, 20 );
			ac = new AddonComponent( 1476 );
			AddComponent( ac, -3, 3, 20 );
			ac = new AddonComponent( 1476 );
			AddComponent( ac, -3, 4, 20 );
			ac = new AddonComponent( 1476 );
			AddComponent( ac, -3, 5, 20 );
			ac = new AddonComponent( 1476 );
			AddComponent( ac, -2, 1, 23 );
			ac = new AddonComponent( 1476 );
			AddComponent( ac, -2, 2, 23 );
			ac = new AddonComponent( 1476 );
			AddComponent( ac, -2, 3, 23 );
			ac = new AddonComponent( 1476 );
			AddComponent( ac, -2, 4, 23 );
			ac = new AddonComponent( 1476 );
			AddComponent( ac, -2, 5, 23 );
			ac = new AddonComponent( 330 );
			AddComponent( ac, -2, 4, 20 );
			ac = new AddonComponent( 330 );
			AddComponent( ac, -1, 4, 20 );
			ac = new AddonComponent( 330 );
			AddComponent( ac, 0, 4, 20 );
			ac = new AddonComponent( 330 );
			AddComponent( ac, 1, 4, 20 );
			ac = new AddonComponent( 330 );
			AddComponent( ac, 2, 4, 20 );
			ac = new AddonComponent( 330 );
			AddComponent( ac, 3, 4, 20 );
			ac = new AddonComponent( 330 );
			AddComponent( ac, 4, 4, 20 );
			ac = new AddonComponent( 1476 );
			AddComponent( ac, -1, 1, 26 );
			ac = new AddonComponent( 1476 );
			AddComponent( ac, -1, 2, 26 );
			ac = new AddonComponent( 1476 );
			AddComponent( ac, -1, 3, 26 );
			ac = new AddonComponent( 1476 );
			AddComponent( ac, -1, 4, 26 );
			ac = new AddonComponent( 1476 );
			AddComponent( ac, -1, 5, 26 );
			ac = new AddonComponent( 330 );
			AddComponent( ac, -1, 4, 23 );
			ac = new AddonComponent( 330 );
			AddComponent( ac, 0, 4, 23 );
			ac = new AddonComponent( 330 );
			AddComponent( ac, 1, 4, 23 );
			ac = new AddonComponent( 330 );
			AddComponent( ac, 2, 4, 23 );
			ac = new AddonComponent( 330 );
			AddComponent( ac, 3, 4, 23 );
			ac = new AddonComponent( 1476 );
			AddComponent( ac, 0, 1, 29 );
			ac = new AddonComponent( 1476 );
			AddComponent( ac, 0, 2, 29 );
			ac = new AddonComponent( 1476 );
			AddComponent( ac, 0, 3, 29 );
			ac = new AddonComponent( 1476 );
			AddComponent( ac, 0, 4, 29 );
			ac = new AddonComponent( 1476 );
			AddComponent( ac, 0, 5, 29 );
			ac = new AddonComponent( 330 );
			AddComponent( ac, 0, 4, 26 );
			ac = new AddonComponent( 330 );
			AddComponent( ac, 1, 4, 26 );
			ac = new AddonComponent( 330 );
			AddComponent( ac, 2, 4, 26 );
			ac = new AddonComponent( 1474 );
			AddComponent( ac, 1, 1, 32 );
			ac = new AddonComponent( 1474 );
			AddComponent( ac, 1, 2, 32 );
			ac = new AddonComponent( 1474 );
			AddComponent( ac, 1, 3, 32 );
			ac = new AddonComponent( 1474 );
			AddComponent( ac, 1, 4, 32 );
			ac = new AddonComponent( 1474 );
			AddComponent( ac, 1, 5, 32 );
			ac = new AddonComponent( 330 );
			AddComponent( ac, 1, 4, 29 );
			ac = new AddonComponent( 1475 );
			AddComponent( ac, 2, 1, 29 );
			ac = new AddonComponent( 1475 );
			AddComponent( ac, 2, 2, 29 );
			ac = new AddonComponent( 1475 );
			AddComponent( ac, 2, 3, 29 );
			ac = new AddonComponent( 1475 );
			AddComponent( ac, 2, 4, 29 );
			ac = new AddonComponent( 1475 );
			AddComponent( ac, 2, 5, 29 );
			ac = new AddonComponent( 1475 );
			AddComponent( ac, 3, 1, 26 );
			ac = new AddonComponent( 1475 );
			AddComponent( ac, 3, 2, 26 );
			ac = new AddonComponent( 1475 );
			AddComponent( ac, 3, 3, 26 );
			ac = new AddonComponent( 1475 );
			AddComponent( ac, 3, 4, 26 );
			ac = new AddonComponent( 1475 );
			AddComponent( ac, 3, 5, 26 );
			ac = new AddonComponent( 1475 );
			AddComponent( ac, 4, 1, 23 );
			ac = new AddonComponent( 1475 );
			AddComponent( ac, 4, 2, 23 );
			ac = new AddonComponent( 1475 );
			AddComponent( ac, 4, 3, 23 );
			ac = new AddonComponent( 1475 );
			AddComponent( ac, 4, 4, 23 );
			ac = new AddonComponent( 1475 );
			AddComponent( ac, 4, 5, 23 );
			ac = new AddonComponent( 1475 );
			AddComponent( ac, 5, 1, 20 );
			ac = new AddonComponent( 1475 );
			AddComponent( ac, 5, 2, 20 );
			ac = new AddonComponent( 1475 );
			AddComponent( ac, 5, 3, 20 );
			ac = new AddonComponent( 1475 );
			AddComponent( ac, 5, 4, 20 );
			ac = new AddonComponent( 1475 );
			AddComponent( ac, 5, 5, 20 );

		}

		public monglowAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class monglowAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new monglowAddon();
			}
		}

		[Constructable]
		public monglowAddonDeed()
		{
			Name = "monglow";
		}

		public monglowAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}