/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class temploAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new temploAddonDeed();
			}
		}

		[ Constructable ]
		public temploAddon()
		{
			AddonComponent ac = null;
			ac = new AddonComponent( 3254 );
			AddComponent( ac, -6, -1, 0 );
			ac = new AddonComponent( 3247 );
			AddComponent( ac, -5, -2, 0 );
			ac = new AddonComponent( 204 );
			AddComponent( ac, -5, -2, 5 );
			ac = new AddonComponent( 203 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, -5, -1, 5 );
			ac = new AddonComponent( 202 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, -4, -2, 5 );
			ac = new AddonComponent( 202 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, -3, -2, 5 );
			ac = new AddonComponent( 1180 );
			AddComponent( ac, -4, -1, 5 );
			ac = new AddonComponent( 4619 );
			AddComponent( ac, -4, -1, 5 );
			ac = new AddonComponent( 1180 );
			AddComponent( ac, -3, -1, 5 );
			ac = new AddonComponent( 204 );
			AddComponent( ac, -2, -3, 5 );
			ac = new AddonComponent( 199 );
			AddComponent( ac, -2, -2, 5 );
			ac = new AddonComponent( 1180 );
			AddComponent( ac, -2, -1, 5 );
			ac = new AddonComponent( 204 );
			AddComponent( ac, -1, -6, 5 );
			ac = new AddonComponent( 203 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, -1, -5, 5 );
			ac = new AddonComponent( 203 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, -1, -4, 5 );
			ac = new AddonComponent( 199 );
			AddComponent( ac, -1, -3, 5 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, -1, -2, 5 );
			ac = new AddonComponent( 3634 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, -1, -2, 10 );
			ac = new AddonComponent( 6571 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, -1, -2, 17 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 202 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 0, -6, 5 );
			ac = new AddonComponent( 202 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 1, -6, 5 );
			ac = new AddonComponent( 202 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 2, -6, 5 );
			ac = new AddonComponent( 1180 );
			AddComponent( ac, 0, -5, 5 );
			ac = new AddonComponent( 1180 );
			AddComponent( ac, 0, -4, 5 );
			ac = new AddonComponent( 1180 );
			AddComponent( ac, 0, -3, 5 );
			ac = new AddonComponent( 1180 );
			AddComponent( ac, 1, -5, 5 );
			ac = new AddonComponent( 1180 );
			AddComponent( ac, 1, -4, 5 );
			ac = new AddonComponent( 1180 );
			AddComponent( ac, 1, -3, 5 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, 0, -2, 0 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 4071 );
			AddComponent( ac, 0, -1, 5 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, 1, -2, 0 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 4072 );
			AddComponent( ac, 1, -1, 5 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, 2, -5, 0 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, 3, -5, 0 );
			ac = new AddonComponent( 1180 );
			AddComponent( ac, 2, -4, 5 );
			ac = new AddonComponent( 1180 );
			AddComponent( ac, 2, -3, 5 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, 2, -2, 0 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 4075 );
			AddComponent( ac, 2, -1, 5 );
			ac = new AddonComponent( 200 );
			AddComponent( ac, 3, -6, 5 );
			ac = new AddonComponent( 203 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 3, -5, 5 );
			ac = new AddonComponent( 203 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 3, -4, 5 );
			ac = new AddonComponent( 203 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 3, -3, 5 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, 3, -4, 0 );
			ac = new AddonComponent( 1180 );
			AddComponent( ac, 3, -3, 5 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, 3, -2, 0 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, 3, -1, 0 );
			ac = new AddonComponent( 3311 );
			AddComponent( ac, 4, -5, 0 );
			ac = new AddonComponent( 3312 );
			AddComponent( ac, 4, -5, 0 );
			ac = new AddonComponent( 3313 );
			AddComponent( ac, 4, -5, 0 );
			ac = new AddonComponent( 202 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 4, -3, 5 );
			ac = new AddonComponent( 202 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 5, -3, 5 );
			ac = new AddonComponent( 3310 );
			AddComponent( ac, 4, -2, 0 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, 4, -2, 0 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, 5, -2, 0 );
			ac = new AddonComponent( 1180 );
			AddComponent( ac, 4, -1, 5 );
			ac = new AddonComponent( 221 );
			AddComponent( ac, 4, -1, 5 );
			ac = new AddonComponent( 215 );
			AddComponent( ac, 5, -2, 5 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, 5, -1, 0 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, 5, -1, 5 );
			ac = new AddonComponent( 3634 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 5, -1, 10 );
			ac = new AddonComponent( 6571 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 5, -1, 17 );
			ac = new AddonComponent( 6815 );
			AddComponent( ac, 5, -1, 17 );
			ac = new AddonComponent( 3314 );
			AddComponent( ac, 6, -2, 0 );
			ac = new AddonComponent( 6814 );
			AddComponent( ac, 6, -2, 17 );
			ac = new AddonComponent( 6460 );
			AddComponent( ac, -5, -2, 25 );
			ac = new AddonComponent( 6460 );
			AddComponent( ac, -4, -2, 25 );
			ac = new AddonComponent( 6460 );
			AddComponent( ac, -3, -2, 25 );
			ac = new AddonComponent( 6460 );
			AddComponent( ac, -2, -2, 25 );
			ac = new AddonComponent( 6460 );
			AddComponent( ac, -5, -1, 28 );
			ac = new AddonComponent( 6460 );
			AddComponent( ac, -4, -1, 28 );
			ac = new AddonComponent( 6460 );
			AddComponent( ac, -3, -1, 28 );
			ac = new AddonComponent( 6460 );
			AddComponent( ac, -2, -1, 28 );
			ac = new AddonComponent( 6459 );
			AddComponent( ac, -1, -6, 25 );
			ac = new AddonComponent( 6459 );
			AddComponent( ac, -1, -5, 25 );
			ac = new AddonComponent( 6459 );
			AddComponent( ac, -1, -4, 25 );
			ac = new AddonComponent( 6459 );
			AddComponent( ac, -1, -3, 25 );
			ac = new AddonComponent( 6459 );
			AddComponent( ac, 0, -6, 28 );
			ac = new AddonComponent( 6459 );
			AddComponent( ac, 0, -5, 28 );
			ac = new AddonComponent( 6459 );
			AddComponent( ac, 0, -4, 28 );
			ac = new AddonComponent( 6459 );
			AddComponent( ac, 0, -3, 28 );
			ac = new AddonComponent( 6462 );
			AddComponent( ac, 1, -6, 31 );
			ac = new AddonComponent( 6462 );
			AddComponent( ac, 1, -5, 31 );
			ac = new AddonComponent( 6462 );
			AddComponent( ac, 1, -4, 31 );
			ac = new AddonComponent( 6462 );
			AddComponent( ac, 1, -3, 31 );
			ac = new AddonComponent( 6457 );
			AddComponent( ac, 2, -6, 28 );
			ac = new AddonComponent( 6457 );
			AddComponent( ac, 2, -5, 28 );
			ac = new AddonComponent( 6457 );
			AddComponent( ac, 2, -4, 28 );
			ac = new AddonComponent( 6457 );
			AddComponent( ac, 2, -3, 28 );
			ac = new AddonComponent( 6457 );
			AddComponent( ac, 3, -6, 25 );
			ac = new AddonComponent( 6457 );
			AddComponent( ac, 3, -5, 25 );
			ac = new AddonComponent( 6457 );
			AddComponent( ac, 3, -4, 25 );
			ac = new AddonComponent( 6457 );
			AddComponent( ac, 3, -3, 25 );
			ac = new AddonComponent( 203 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, -5, 0, 5 );
			ac = new AddonComponent( 203 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, -5, 1, 5 );
			ac = new AddonComponent( 201 );
			AddComponent( ac, -5, 2, 5 );
			ac = new AddonComponent( 1180 );
			AddComponent( ac, -4, 0, 5 );
			ac = new AddonComponent( 4618 );
			AddComponent( ac, -4, 0, 5 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, -4, 1, 0 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, -4, 2, 0 );
			ac = new AddonComponent( 202 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, -4, 2, 5 );
			ac = new AddonComponent( 202 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, -3, 2, 5 );
			ac = new AddonComponent( 202 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, -2, 2, 5 );
			ac = new AddonComponent( 3310 );
			AddComponent( ac, -4, 3, 0 );
			ac = new AddonComponent( 3308 );
			AddComponent( ac, -4, 3, 0 );
			ac = new AddonComponent( 3308 );
			AddComponent( ac, -3, 3, 0 );
			ac = new AddonComponent( 3309 );
			AddComponent( ac, -4, 3, 0 );
			ac = new AddonComponent( 1180 );
			AddComponent( ac, -3, 0, 5 );
			ac = new AddonComponent( 1180 );
			AddComponent( ac, -3, 1, 5 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, -3, 2, 0 );
			ac = new AddonComponent( 3313 );
			AddComponent( ac, -3, 3, 8 );
			ac = new AddonComponent( 1180 );
			AddComponent( ac, -2, 0, 5 );
			ac = new AddonComponent( 1180 );
			AddComponent( ac, -2, 1, 5 );
			ac = new AddonComponent( 1180 );
			AddComponent( ac, -2, 2, 5 );
			ac = new AddonComponent( 3247 );
			AddComponent( ac, -2, 0, 0 );
			ac = new AddonComponent( 203 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, -2, 3, 5 );
			ac = new AddonComponent( 203 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, -2, 4, 5 );
			ac = new AddonComponent( 231 );
			AddComponent( ac, -2, 4, 1 );
			ac = new AddonComponent( 231 );
			AddComponent( ac, -2, 4, 3 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, -1, 2, 0 );
			ac = new AddonComponent( 3314 );
			AddComponent( ac, -1, 3, 0 );
			ac = new AddonComponent( 1180 );
			AddComponent( ac, -1, 3, 5 );
			ac = new AddonComponent( 1180 );
			AddComponent( ac, 0, 3, 5 );
			ac = new AddonComponent( 1180 );
			AddComponent( ac, 1, 3, 5 );
			ac = new AddonComponent( 1180 );
			AddComponent( ac, 2, 3, 5 );
			ac = new AddonComponent( 1180 );
			AddComponent( ac, 3, 3, 5 );
			ac = new AddonComponent( 1180 );
			AddComponent( ac, 4, 3, 5 );
			ac = new AddonComponent( 1180 );
			AddComponent( ac, 5, 3, 5 );
			ac = new AddonComponent( 1180 );
			AddComponent( ac, 6, 3, 5 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, -1, 4, 0 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, 0, 4, 0 );
			ac = new AddonComponent( 216 );
			AddComponent( ac, -1, 4, 5 );
			ac = new AddonComponent( 3310 );
			AddComponent( ac, -1, 5, 0 );
			ac = new AddonComponent( 6816 );
			AddComponent( ac, -1, 5, 17 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, 0, 2, 0 );
			ac = new AddonComponent( 4070 );
			AddComponent( ac, 0, 0, 5 );
			ac = new AddonComponent( 4073 );
			AddComponent( ac, 0, 1, 5 );
			ac = new AddonComponent( 222 );
			AddComponent( ac, 0, 3, 5 );
			ac = new AddonComponent( 222 );
			AddComponent( ac, 1, 3, 5 );
			ac = new AddonComponent( 222 );
			AddComponent( ac, 2, 3, 5 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, 0, 4, 5 );
			ac = new AddonComponent( 3634 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 0, 4, 10 );
			ac = new AddonComponent( 6571 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 0, 4, 17 );
			ac = new AddonComponent( 6817 );
			AddComponent( ac, 0, 4, 17 );
			ac = new AddonComponent( 4074 );
			AddComponent( ac, 1, 0, 5 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, 1, 2, 0 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, 1, 3, 0 );
			ac = new AddonComponent( 4076 );
			AddComponent( ac, 1, 1, 5 );
			ac = new AddonComponent( 3245 );
			AddComponent( ac, 1, 4, 0 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 4078 );
			AddComponent( ac, 2, 0, 5 );
			ac = new AddonComponent( 4077 );
			AddComponent( ac, 2, 1, 5 );
			ac = new AddonComponent( 1180 );
			AddComponent( ac, 2, 2, 5 );
			ac = new AddonComponent( 1180 );
			AddComponent( ac, 3, 2, 5 );
			ac = new AddonComponent( 1180 );
			AddComponent( ac, 4, 2, 5 );
			ac = new AddonComponent( 1180 );
			AddComponent( ac, 5, 2, 5 );
			ac = new AddonComponent( 1180 );
			AddComponent( ac, 6, 2, 5 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, 2, 3, 0 );
			ac = new AddonComponent( 1866 );
			AddComponent( ac, 2, 4, 0 );
			ac = new AddonComponent( 1865 );
			AddComponent( ac, 2, 5, 0 );
			ac = new AddonComponent( 1869 );
			AddComponent( ac, 2, 6, 0 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, 3, 0, 0 );
			ac = new AddonComponent( 1180 );
			AddComponent( ac, 3, 1, 5 );
			ac = new AddonComponent( 1180 );
			AddComponent( ac, 4, 1, 5 );
			ac = new AddonComponent( 1180 );
			AddComponent( ac, 3, 4, 5 );
			ac = new AddonComponent( 1180 );
			AddComponent( ac, 3, 5, 5 );
			ac = new AddonComponent( 1180 );
			AddComponent( ac, 4, 4, 5 );
			ac = new AddonComponent( 1180 );
			AddComponent( ac, 4, 5, 5 );
			ac = new AddonComponent( 219 );
			AddComponent( ac, 3, 4, 11 );
			ac = new AddonComponent( 1823 );
			AddComponent( ac, 3, 6, 0 );
			ac = new AddonComponent( 1823 );
			AddComponent( ac, 4, 6, 0 );
			ac = new AddonComponent( 1180 );
			AddComponent( ac, 4, 0, 5 );
			ac = new AddonComponent( 221 );
			AddComponent( ac, 4, 0, 5 );
			ac = new AddonComponent( 221 );
			AddComponent( ac, 4, 1, 5 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, 4, 0, 0 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, 4, 1, 0 );
			ac = new AddonComponent( 218 );
			AddComponent( ac, 4, 4, 11 );
			ac = new AddonComponent( 3244 );
			AddComponent( ac, 5, 0, 0 );
			ac = new AddonComponent( 1866 );
			AddComponent( ac, 5, 1, 0 );
			ac = new AddonComponent( 219 );
			AddComponent( ac, 5, 2, 12 );
			ac = new AddonComponent( 217 );
			AddComponent( ac, 5, 3, 11 );
			ac = new AddonComponent( 1953 );
			AddComponent( ac, 5, 4, 0 );
			ac = new AddonComponent( 212 );
			AddComponent( ac, 5, 4, 11 );
			ac = new AddonComponent( 1846 );
			AddComponent( ac, 5, 5, 0 );
			ac = new AddonComponent( 1867 );
			AddComponent( ac, 5, 6, 0 );
			ac = new AddonComponent( 1847 );
			AddComponent( ac, 6, 1, 0 );
			ac = new AddonComponent( 1823 );
			AddComponent( ac, 6, 4, 0 );
			ac = new AddonComponent( 1868 );
			AddComponent( ac, 7, 1, 0 );
			ac = new AddonComponent( 1846 );
			AddComponent( ac, 7, 2, 0 );
			ac = new AddonComponent( 1846 );
			AddComponent( ac, 7, 3, 0 );
			ac = new AddonComponent( 1867 );
			AddComponent( ac, 7, 4, 0 );
			ac = new AddonComponent( 6461 );
			AddComponent( ac, -5, 0, 31 );
			ac = new AddonComponent( 6461 );
			AddComponent( ac, -4, 0, 31 );
			ac = new AddonComponent( 6461 );
			AddComponent( ac, -3, 0, 31 );
			ac = new AddonComponent( 6461 );
			AddComponent( ac, -2, 0, 31 );
			ac = new AddonComponent( 6458 );
			AddComponent( ac, -5, 1, 28 );
			ac = new AddonComponent( 6458 );
			AddComponent( ac, -4, 1, 28 );
			ac = new AddonComponent( 6458 );
			AddComponent( ac, -3, 1, 28 );
			ac = new AddonComponent( 6458 );
			AddComponent( ac, -2, 1, 28 );
			ac = new AddonComponent( 6458 );
			AddComponent( ac, -5, 2, 25 );
			ac = new AddonComponent( 6458 );
			AddComponent( ac, -4, 2, 25 );
			ac = new AddonComponent( 6458 );
			AddComponent( ac, -3, 2, 25 );
			ac = new AddonComponent( 6458 );
			AddComponent( ac, -2, 2, 25 );
			ac = new AddonComponent( 225 );
			AddComponent( ac, 4, 4, 31 );
			ac = new AddonComponent( 225 );
			AddComponent( ac, 5, 3, 31 );
			ac = new AddonComponent( 224 );
			AddComponent( ac, 5, 4, 31 );
			ac = new AddonComponent( 227 );
			AddComponent( ac, 5, 4, 31 );

		}

		public temploAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class temploAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new temploAddon();
			}
		}

		[Constructable]
		public temploAddonDeed()
		{
			Name = "templo";
		}

		public temploAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}