
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class TrinsicBridge1Addon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {100, -1, 5, 15}, {100, 2, 5, 15}, {100, 2, 4, 15}// 1	2	3	
			, {100, 2, 3, 15}, {100, 2, 2, 15}, {100, 2, 1, 15}// 4	5	6	
			, {100, -1, 4, 15}, {100, -1, 3, 15}, {100, -1, 2, 15}// 7	8	9	
			, {100, -1, 1, 15}, {1872, 2, 3, 5}, {1872, 2, 3, 0}// 10	11	12	
			, {1872, 2, 6, 6}, {1872, 1, 6, 6}, {1872, 0, 6, 6}// 13	14	15	
			, {1873, 1, 7, 5}, {1873, 2, 7, 5}, {1873, 0, 7, 5}// 16	17	18	
			, {1873, 0, 6, 10}, {1873, 1, 6, 10}, {1873, 2, 6, 10}// 19	20	21	
			, {1872, 2, 5, 10}, {1872, 2, 4, 10}, {1872, 2, 3, 10}// 22	23	24	
			, {1872, 2, 2, 10}, {1872, 2, 1, 10}, {1872, 1, 5, 10}// 25	26	27	
			, {1872, 1, 4, 10}, {1872, 1, 3, 10}, {1872, 1, 2, 10}// 28	29	30	
			, {1872, 1, 1, 10}, {1872, 0, 5, 10}, {1872, 0, 4, 10}// 31	32	33	
			, {1872, 0, 3, 10}, {1872, 0, 2, 10}, {1872, 0, 1, 10}// 34	35	36	
			, {1872, 0, -1, 10}, {100, 2, 0, 15}, {100, 2, -1, 15}// 37	38	39	
			, {100, 2, -2, 15}, {100, 2, -3, 15}, {100, 2, -4, 15}// 40	41	42	
			, {100, -1, 0, 15}, {100, -1, -1, 15}, {100, -1, -2, 15}// 43	44	45	
			, {100, -1, -3, 15}, {100, -1, -4, 15}, {1872, 2, -1, 5}// 46	47	48	
			, {1872, 2, -1, 0}, {1872, 2, -4, 10}, {1875, 0, -5, 10}// 49	50	51	
			, {1872, 2, 0, 10}, {1872, 2, -1, 10}, {1872, 2, -2, 10}// 52	53	54	
			, {1872, 2, -3, 10}, {1872, 1, 0, 10}, {1872, 1, -1, 10}// 55	56	57	
			, {1872, 1, -2, 10}, {1872, 1, -3, 10}, {1872, 1, -4, 10}// 58	59	60	
			, {1872, 0, 0, 10}, {1872, 0, -2, 10}, {1872, 0, -3, 10}// 61	62	63	
			, {1872, 0, -4, 10}, {1875, 2, -5, 10}, {1875, 1, -5, 10}// 64	65	66	
			, {1872, 0, -5, 5}, {1872, 1, -5, 5}, {1875, 0, -6, 5}// 67	68	69	
			, {1875, 1, -6, 5}, {1875, 2, -6, 5}, {1872, 2, -5, 5}// 70	71	72	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new TrinsicBridge1AddonDeed();
			}
		}

		[ Constructable ]
		public TrinsicBridge1Addon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public TrinsicBridge1Addon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class TrinsicBridge1AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new TrinsicBridge1Addon();
			}
		}

		[Constructable]
		public TrinsicBridge1AddonDeed()
		{
			Name = "TrinsicBridge1";
		}

		public TrinsicBridge1AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}