
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class TrinsicBridge2Addon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {1874, 4, 0, 5}, {1874, 4, 1, 5}, {1874, 4, 2, 5}// 1	2	3	
			, {99, 3, 2, 10}, {99, 2, 2, 10}, {99, 1, 2, 10}// 4	5	6	
			, {99, 0, 2, 10}, {99, -1, 2, 10}, {99, -2, 2, 10}// 7	8	9	
			, {99, -3, 2, 10}, {99, 3, -1, 10}, {99, 2, -1, 10}// 10	11	12	
			, {99, 1, -1, 10}, {99, 0, -1, 10}, {99, -1, -1, 10}// 13	14	15	
			, {99, -2, -1, 10}, {99, -3, -1, 10}, {1872, 2, 2, 0}// 16	17	18	
			, {1872, -1, 2, 0}, {1872, 1, 2, 0}, {1872, 0, 2, 0}// 19	20	21	
			, {1872, -3, 2, 5}, {1872, -3, 1, 5}, {1872, 3, 2, 5}// 22	23	24	
			, {1872, 3, 1, 5}, {1872, 3, 0, 5}, {1872, 2, 2, 5}// 25	26	27	
			, {1872, 2, 1, 5}, {1872, 2, 0, 5}, {1872, 1, 2, 5}// 28	29	30	
			, {1872, 1, 1, 5}, {1872, 1, 0, 5}, {1872, 0, 2, 5}// 31	32	33	
			, {1872, 0, 1, 5}, {1872, 0, 0, 5}, {1872, -1, 2, 5}// 34	35	36	
			, {1872, -1, 1, 5}, {1872, -1, 0, 5}, {1872, -2, 2, 5}// 37	38	39	
			, {1872, -2, 1, 5}, {1872, -2, 0, 5}, {1872, -3, 0, 5}// 40	41	42	
			, {1876, -4, 0, 5}, {1876, -4, 1, 5}, {1876, -4, 2, 5}// 43	44	45	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new TrinsicBridge2AddonDeed();
			}
		}

		[ Constructable ]
		public TrinsicBridge2Addon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public TrinsicBridge2Addon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class TrinsicBridge2AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new TrinsicBridge2Addon();
			}
		}

		[Constructable]
		public TrinsicBridge2AddonDeed()
		{
			Name = "TrinsicBridge2";
		}

		public TrinsicBridge2AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}