
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class VTableForTwoEAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {11516, 0, 3, 0}, {11516, 0, -2, 0}, {6377, 0, 0, 12}// 1	2	6	
			, {10012, -1, -2, 0}, {10015, 0, -3, 0}, {9354, -1, -3, 0}// 7	8	9	
			, {11514, 0, 2, 0}, {10012, -1, 2, 0}, {10012, -1, 1, 0}// 10	11	12	
			, {10012, -1, 0, 0}, {10012, -1, -1, 0}, {11514, 0, -1, 0}// 13	14	15	
			, {11514, 0, -2, 0}, {11514, 0, 1, 0}, {10015, 0, 2, 0}// 16	17	18	
			, {2787, 1, 1, 0}, {2789, -1, 1, 0}, {2794, 0, 1, 0}// 19	20	21	
			, {2791, -1, 0, 0}, {2793, 1, 0, 0}, {2795, 0, 0, 0}// 22	23	24	
			, {2788, -1, -1, 0}, {2790, 1, -1, 0}, {2792, 0, -1, 0}// 25	26	27	
			, {2888, 0, 0, 8}, {11517, 0, 3, 0}, {11521, 1, -2, 0}// 28	29	30	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new VTableForTwoEAddonDeed();
			}
		}

		[ Constructable ]
		public VTableForTwoEAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 2899, 0, -1, 0, 1153, -1, "", 1);// 3
			AddComplexComponent( (BaseAddon) this, 2900, 0, 1, 0, 1153, -1, "", 1);// 4
			AddComplexComponent( (BaseAddon) this, 2868, 0, 0, 0, 1153, -1, "", 1);// 5

		}

		public VTableForTwoEAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class VTableForTwoEAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new VTableForTwoEAddon();
			}
		}

		[Constructable]
		public VTableForTwoEAddonDeed()
		{
			Name = "VTableForTwoE";
		}

		public VTableForTwoEAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}