
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class VTableforTwoSAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {11514, 3, 0, 0}, {11519, 3, 0, 0}, {11514, -2, 0, 0}// 1	2	3	
			, {6377, 0, 0, 11}, {10015, 2, -1, 0}, {10015, 1, -1, 0}// 7	8	9	
			, {10015, 0, -1, 0}, {10015, -1, -1, 0}, {10015, -2, -1, 0}// 10	11	12	
			, {11516, -2, 0, 0}, {11516, 2, 0, 0}, {10012, -3, 0, 0}// 13	14	15	
			, {10012, 2, 0, 0}, {11523, -2, 1, 0}, {11516, 2, 0, 0}// 16	17	18	
			, {11516, 1, 0, 0}, {11516, -1, 0, 0}, {2888, 0, 0, 8}// 19	20	21	
			, {2787, 1, 1, 0}, {2788, -1, -1, 0}, {2789, -1, 1, 0}// 22	23	24	
			, {2790, 1, -1, 0}, {2791, -1, 0, 0}, {2792, 0, -1, 0}// 25	26	27	
			, {2793, 1, 0, 0}, {2794, 0, 1, 0}, {2795, 0, 0, 0}// 28	29	30	
			, {9354, -3, -1, 0}// 31	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new VTableforTwoSAddonDeed();
			}
		}

		[ Constructable ]
		public VTableforTwoSAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 2901, 1, 0, 0, 1153, -1, "", 1);// 4
			AddComplexComponent( (BaseAddon) this, 2898, -1, 0, 0, 1153, -1, "", 1);// 5
			AddComplexComponent( (BaseAddon) this, 2868, 0, 0, 0, 1153, -1, "", 1);// 6

		}

		public VTableforTwoSAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class VTableforTwoSAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new VTableforTwoSAddon();
			}
		}

		[Constructable]
		public VTableforTwoSAddonDeed()
		{
			Name = "VTableforTwoS";
		}

		public VTableforTwoSAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}