/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class AGBloodyCouchSouthAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new AGBloodyCouchSouthAddonDeed();
			}
		}

		[ Constructable ]
		public AGBloodyCouchSouthAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 1848 );
			ac.Hue = 1109;
			ac.Name = "HellCoutch";
			AddComponent( ac, -2, 0, 0 );
			ac = new AddonComponent( 1848 );
			ac.Hue = 1109;
			ac.Name = "HellCoutch";
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 1848 );
			ac.Hue = 1109;
			ac.Name = "HellCoutch";
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 1848 );
			ac.Hue = 1109;
			ac.Name = "HellCoutch";
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 1848 );
			ac.Hue = 1109;
			ac.Name = "HellCoutch";
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 5168 );
			ac.Light = LightType.NorthBig2;
			ac.Hue = 37;
			ac.Name = "BloodCandle";
			AddComponent( ac, 2, 0, 7 );
			ac = new AddonComponent( 5168 );
			ac.Light = LightType.NorthBig;
			ac.Hue = 37;
			ac.Name = "BloodCandle";
			AddComponent( ac, -2, 0, 7 );
			ac = new AddonComponent( 4650 );
			ac.Hue = 37;
			AddComponent( ac, 2, 0, 5 );
			ac = new AddonComponent( 4650 );
			ac.Hue = 37;
			AddComponent( ac, -2, 0, 5 );
			ac = new AddonComponent( 4468 );
			ac.Hue = 1102;
			ac.Name = "GraveOfMistressFate-Angel";
			AddComponent( ac, 1, 0, 7 );
			ac = new AddonComponent( 4468 );
			ac.Hue = 1102;
			ac.Name = "GeaveOfMasterNeedils-Kain";
			AddComponent( ac, -1, 0, 7 );
			ac = new AddonComponent( 5743 );
			ac.Name = "WhipOfTheMistress";
			AddComponent( ac, 0, 0, 7 );

		}

		public AGBloodyCouchSouthAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class AGBloodyCouchSouthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new AGBloodyCouchSouthAddon();
			}
		}

		[Constructable]
		public AGBloodyCouchSouthAddonDeed()
		{
			Name = "AG Bloody Couch South";
		}

		public AGBloodyCouchSouthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}