
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class WellAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {177, -1, 0, 0}, {190, -1, 1, 0}, {189, 1, 1, 0}// 1	2	3	
			, {191, 0, 1, 0}, {190, -1, 0, 0}, {190, 1, 0, 0}// 4	5	6	
			, {191, 1, -1, 0}, {191, 0, -1, 0}, {177, 1, 0, 0}// 7	8	9	
			, {13522, 0, 0, 0}, {13522, 0, 1, 0}, {13522, 1, 0, 0}// 10	11	12	
			, {13522, 1, 1, 0}, {11347, 0, 1, 15}, {11345, 1, 0, 15}// 13	14	15	
			, {11347, 0, 0, 15}, {5368, 1, 2, 10}, {11345, 1, 1, 15}// 16	17	18	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new WellAddonDeed();
			}
		}

		[ Constructable ]
		public WellAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public WellAddon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class WellAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new WellAddon();
			}
		}

		[Constructable]
		public WellAddonDeed()
		{
			Name = "Well";
		}

		public WellAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}