/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class AGBloodyCouchWestAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new AGBloodyCouchWestAddonDeed();
			}
		}

		[ Constructable ]
		public AGBloodyCouchWestAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 1848 );
			ac.Hue = 1109;
			ac.Name = "BloodyCoutch";
			AddComponent( ac, 0, -2, 0 );
			ac = new AddonComponent( 1848 );
			ac.Hue = 1109;
			ac.Name = "BloodyCoutch";
			AddComponent( ac, 0, 2, 0 );
			ac = new AddonComponent( 4635 );
			ac.Hue = 2106;
			ac.Name = "BloodyCoutch";
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 4635 );
			ac.Hue = 2106;
			ac.Name = "BloodyCoutch";
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 4635 );
			ac.Hue = 2106;
			ac.Name = "BloodyCoutch";
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 6884 );
			AddComponent( ac, 0, -2, 5 );

		}

		public AGBloodyCouchWestAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class AGBloodyCouchWestAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new AGBloodyCouchWestAddon();
			}
		}

		[Constructable]
		public AGBloodyCouchWestAddonDeed()
		{
			Name = "AG Bloody Couch West";
		}

		public AGBloodyCouchWestAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}