/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Addons
{
	public class CatapultWestAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new CatapultWestAddonDeed();
			}
		}

		[ Constructable ]
		public CatapultWestAddon()
		{
			AddComponent( new AddonComponent( 5820 ), 1, 0, 0 );
			AddComponent( new AddonComponent( 5831 ), 1, -1, 0 );
			AddComponent( new AddonComponent( 5822 ), 0, -1, 0 );
			AddComponent( new AddonComponent( 5823 ), -2, -1, 0 );
			AddComponent( new AddonComponent( 5824 ), -2, 0, 0 );
			AddComponent( new AddonComponent( 5819 ), 2, -1, 0 );
			AddComponent( new AddonComponent( 5818 ), 2, 0, 0 );
			AddComponent( new AddonComponent( 5825 ), -2, 1, 0 );
			AddComponent( new AddonComponent( 5841 ), -1, -1, 0 );
			AddComponent( new AddonComponent( 5821 ), 0, 1, 0 );
			AddComponent( new AddonComponent( 5836 ), -1, 1, 0 );
			AddComponent( new AddonComponent( 5817 ), 2, 1, 0 );
			AddComponent( new AddonComponent( 5846 ), 2, 1, 0 );
			AddComponent( new AddonComponent( 5826 ), 1, 1, 0 );
		}

		public CatapultWestAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class CatapultWestAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new CatapultWestAddon();
			}
		}

		[Constructable]
		public CatapultWestAddonDeed()
		{
			Name = "CatapultWest";
		}

		public CatapultWestAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}