/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Addons
{
	public class CatapultSouthAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new CatapultSouthAddonDeed();
			}
		}

		[ Constructable ]
		public CatapultSouthAddon()
		{
			AddComponent( new AddonComponent( 5716 ), 1, 0, 0 );
			AddComponent( new AddonComponent( 5707 ), -1, 1, 0 );
			AddComponent( new AddonComponent( 5721 ), -1, 0, 0 );
			AddComponent( new AddonComponent( 5708 ), -1, -1, 0 );
			AddComponent( new AddonComponent( 5709 ), 0, -1, 0 );
			AddComponent( new AddonComponent( 5706 ), 1, -1, 0 );
			AddComponent( new AddonComponent( 5711 ), 1, 2, 0 );
			AddComponent( new AddonComponent( 5731 ), 1, 2, 0 );
			AddComponent( new AddonComponent( 5705 ), 0, 2, 0 );
			AddComponent( new AddonComponent( 5726 ), -1, 2, 0 );
			AddComponent( new AddonComponent( 5704 ), 0, 0, 0 );
			AddComponent( new AddonComponent( 5710 ), 1, 1, 0 );
		}

		public CatapultSouthAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class CatapultSouthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new CatapultSouthAddon();
			}
		}

		[Constructable]
		public CatapultSouthAddonDeed()
		{
			Name = "CatapultSouth";
		}

		public CatapultSouthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}